# -*- coding: utf-8 -*-
"""极快 AOT · C 中间码生成器（T-M6-A02 · ADR-19）。

把**已通过 subset_gate.check** 的 AST 翻译成可被 gcc -std=c11 编译的 C 源码。
调用方有义务先过门禁；本模块对子集外节点一律抛 CodegenError，而不是「尽力
翻译」——静默产出语义不对的产物比报错糟糕得多。

类型策略（动态 → 静态的降级方案）
--------------------------------
极快是动态类型，C 是静态类型。第一版用 tagged union（见 _C_RUNTIME 里的
JKValue）：所有运算走运行时辅助函数（jk_add / jk_lt / ...），在函数内部按
tag 分派，相当于把解释器的动态派发下沉到 C 层。代价是拿不到静态类型特化的
性能上限，收益是语义与解释器一致、实现量小、可审计。

人民币精度（ADR-19 硬要求）
--------------------------
**绝不用 double 存金额。** JK_RMB 用 long long 存「分」：￥99.90 → 9990。
字面量的「元 → 分」换算在 Python 侧用 Decimal 精确完成，所以字面量零误差。
只有运行时「金额 × 浮点因子」这类混算才会退化到 double 中转，该边界写进了
docs/AOT.md 局限清单。

中文字符串
----------
C 源码里直接写 UTF-8 字节转义（反斜杠 x 加两位十六进制），不依赖编译器的
源字符集推断。Windows 下 main() 开头调用 SetConsoleOutputCP(65001)，保证
控制台按 UTF-8 渲染；重定向到管道/文件时本来就是原始字节，不受影响。

浮点打印
--------
解释器用 Python 的 str(float)，即最短往返表示（repr）。C 的 %g 没有这个
语义，所以运行时用「精度 1..17 逐级尝试 + strtod 往返校验」复现它，并对
整数值浮点补 .0（Python 打印 3.0 而非 3）。
"""

from __future__ import annotations

from decimal import ROUND_HALF_UP, Decimal
from typing import Dict, List, Set

from jikuai.ast_nodes import (
    Assign,
    BoolLit,
    Call,
    Define,
    Ident,
    MoneyLit,
    NilLit,
    Node,
    NumberLit,
    Program,
    StringLit,
)

from .subset_gate import SUPPORTED_VERBS


class CodegenError(Exception):
    """codegen 拒绝翻译。正常流程下不该触发——应先被 subset_gate 拦住。"""


# ---------------------------------------------------------------------------
# 动词 → 运行时函数名
# ---------------------------------------------------------------------------

#: 二元动词 → C 运行时函数。口语化别名与本名共用同一实现。
_BINARY_OPS: Dict[str, str] = {
    "加": "jk_add", "加上": "jk_add",
    "减": "jk_sub", "减去": "jk_sub",
    "乘": "jk_mul", "乘以": "jk_mul",
    "除": "jk_div", "除以": "jk_div",
    "取余": "jk_mod",
    "幂": "jk_pow",
    "整除": "jk_floordiv",
    "等于": "jk_eq",
    "不等于": "jk_ne",
    "大于": "jk_gt",
    "小于": "jk_lt",
    "大于等于": "jk_ge",
    "小于等于": "jk_le",
    "且": "jk_and",
    "或": "jk_or",
}

#: 一元动词 → C 运行时函数。
_UNARY_OPS: Dict[str, str] = {
    "负": "jk_neg",
    "绝对值": "jk_abs",
    "非": "jk_not",
}

# 自检：动词映射必须恰好覆盖受支持白名单（打印单独作为语句处理）。
assert set(_BINARY_OPS) | set(_UNARY_OPS) | {"打印"} == set(SUPPORTED_VERBS), (
    "codegen 动词映射与 subset_gate.SUPPORTED_VERBS 不一致"
)


# ---------------------------------------------------------------------------
# C 运行时（prelude）—— 原始字符串，内部反斜杠不被 Python 处理
# ---------------------------------------------------------------------------

_C_RUNTIME = r'''/* ===========================================================
 * 极快 AOT 生成的 C 中间码 —— 自动生成，请勿手工编辑
 * Generated by jikuai_aot (Experimental, ADR-19)
 * =========================================================== */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#ifdef _WIN32
#include <windows.h>
#endif

/* ---------- 值表示：tagged union ---------- */

enum JKTag {
    JK_NIL = 0,
    JK_INT = 1,
    JK_FLOAT = 2,
    JK_STR = 3,
    JK_BOOL = 4,
    JK_RMB = 5      /* v.fen 存「分」，绝不用 double 存金额 */
};

typedef struct {
    int tag;
    union {
        long long i;
        double d;
        const char *s;
        int b;
        long long fen;
    } v;
} JKValue;

static JKValue jk_nil(void)            { JKValue r; r.tag = JK_NIL;   r.v.i = 0;   return r; }
static JKValue jk_int(long long x)     { JKValue r; r.tag = JK_INT;   r.v.i = x;   return r; }
static JKValue jk_float(double x)      { JKValue r; r.tag = JK_FLOAT; r.v.d = x;   return r; }
static JKValue jk_str(const char *x)   { JKValue r; r.tag = JK_STR;   r.v.s = x;   return r; }
static JKValue jk_bool(int x)          { JKValue r; r.tag = JK_BOOL;  r.v.b = x ? 1 : 0; return r; }
static JKValue jk_rmb(long long fen)   { JKValue r; r.tag = JK_RMB;   r.v.fen = fen;     return r; }

/* ---------- 错误处理：与解释器一样「立刻停」 ---------- */

static void jk_fatal(const char *msg)
{
    fflush(stdout);
    fprintf(stderr, "%s\n", msg);
    exit(1);
}

/* ---------- 类型判定与取值 ---------- */

static int jk_is_num(JKValue a)
{
    return a.tag == JK_INT || a.tag == JK_FLOAT || a.tag == JK_BOOL;
}

static long long jk_as_int(JKValue a)
{
    switch (a.tag) {
    case JK_INT:   return a.v.i;
    case JK_BOOL:  return (long long)a.v.b;
    case JK_FLOAT: return (long long)a.v.d;
    default:       jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe9\x9c\x80\xe8\xa6\x81\xe6\x95\xb4\xe6\x95\xb0"); return 0;
    }
}

static double jk_as_double(JKValue a)
{
    switch (a.tag) {
    case JK_INT:   return (double)a.v.i;
    case JK_BOOL:  return (double)a.v.b;
    case JK_FLOAT: return a.v.d;
    case JK_RMB:   return (double)a.v.fen / 100.0;
    default:       jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe9\x9c\x80\xe8\xa6\x81\xe6\x95\xb0\xe5\x80\xbc"); return 0.0;
    }
}

/* 数值 → 分，四舍五入（ROUND_HALF_UP，与中国会计惯例一致） */
static long long jk_to_fen(JKValue a)
{
    double x;
    if (a.tag == JK_RMB) return a.v.fen;
    x = jk_as_double(a) * 100.0;
    return (long long)(x >= 0 ? floor(x + 0.5) : -floor(-x + 0.5));
}

/* Python 真值语义：空 / 假 / 0 / 0.0 / "" 为假；人民币对象恒为真 */
static int jk_truthy(JKValue a)
{
    switch (a.tag) {
    case JK_NIL:   return 0;
    case JK_INT:   return a.v.i != 0;
    case JK_BOOL:  return a.v.b != 0;
    case JK_FLOAT: return a.v.d != 0.0;
    case JK_STR:   return a.v.s != NULL && a.v.s[0] != '\0';
    case JK_RMB:   return 1;
    default:       return 0;
    }
}

/* ---------- 字符串拼接 ----------
 * 设计取舍：AOT 子集是直线代码、进程短命，故拼接结果故意不释放
 * （arena 语义）。这条写进 docs/AOT.md 局限清单。
 */
static const char *jk_concat(const char *a, const char *b)
{
    size_t la = strlen(a), lb = strlen(b);
    char *r = (char *)malloc(la + lb + 1);
    if (r == NULL) jk_fatal("\xe5\x86\x85\xe5\xad\x98\xe4\xb8\x8d\xe8\xb6\xb3");
    memcpy(r, a, la);
    memcpy(r + la, b, lb);
    r[la + lb] = '\0';
    return r;
}

/* ---------- 浮点格式化：复现 Python str(float) 的最短往返表示 ---------- */

static void jk_fmt_double(double d, char *buf, size_t n)
{
    int p;
    size_t len;

    if (isnan(d)) { snprintf(buf, n, "nan"); return; }
    if (isinf(d)) { snprintf(buf, n, d < 0 ? "-inf" : "inf"); return; }

    for (p = 1; p <= 17; p++) {
        snprintf(buf, n, "%.*g", p, d);
        if (strtod(buf, NULL) == d) break;
    }
    /* Python 打印整数值浮点为 3.0，%g 给的是 3 */
    if (strpbrk(buf, ".eE") == NULL) {
        len = strlen(buf);
        if (len + 2 < n) {
            buf[len] = '.';
            buf[len + 1] = '0';
            buf[len + 2] = '\0';
        }
    }
}

/* ---------- 打印 ---------- */

static void jk_write(JKValue a)
{
    char buf[64];
    long long fen, yuan, cents;

    switch (a.tag) {
    case JK_NIL:
        fputs("\xe7\xa9\xba", stdout);                  /* 空 */
        break;
    case JK_INT:
        printf("%lld", a.v.i);
        break;
    case JK_BOOL:
        fputs(a.v.b ? "\xe7\x9c\x9f" : "\xe5\x81\x87", stdout);  /* 真 / 假 */
        break;
    case JK_FLOAT:
        jk_fmt_double(a.v.d, buf, sizeof(buf));
        fputs(buf, stdout);
        break;
    case JK_STR:
        fputs(a.v.s, stdout);
        break;
    case JK_RMB:
        fen = a.v.fen;
        if (fen < 0) { fputs("-", stdout); fen = -fen; }
        yuan = fen / 100;
        cents = fen % 100;
        printf("\xef\xbf\xa5%lld.%02lld", yuan, cents); /* 全角￥ */
        break;
    default:
        jk_fatal("\xe5\x86\x85\xe9\x83\xa8\xe9\x94\x99\xe8\xaf\xaf");
    }
}

static void jk_print(int argc, JKValue *argv)
{
    int i;
    for (i = 0; i < argc; i++) {
        if (i > 0) fputs(" ", stdout);
        jk_write(argv[i]);
    }
    fputs("\n", stdout);
}

/* ---------- 算术 ---------- */

static const char *JK_ERR_DIV0 = "\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe9\x99\xa4\xe6\x95\xb0\xe4\xb8\x8d\xe8\x83\xbd\xe4\xb8\xba\xe9\x9b\xb6";

static JKValue jk_add(JKValue a, JKValue b)
{
    if (a.tag == JK_STR && b.tag == JK_STR)
        return jk_str(jk_concat(a.v.s, b.v.s));
    if (a.tag == JK_STR || b.tag == JK_STR)
        jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe5\x8f\xaa\xe8\x83\xbd\xe4\xb8\x8e\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe7\x9b\xb8\xe5\x8a\xa0");
    if (a.tag == JK_RMB || b.tag == JK_RMB)
        return jk_rmb(jk_to_fen(a) + jk_to_fen(b));
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT)
        return jk_float(jk_as_double(a) + jk_as_double(b));
    return jk_int(jk_as_int(a) + jk_as_int(b));
}

static JKValue jk_sub(JKValue a, JKValue b)
{
    if (a.tag == JK_RMB || b.tag == JK_RMB)
        return jk_rmb(jk_to_fen(a) - jk_to_fen(b));
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT)
        return jk_float(jk_as_double(a) - jk_as_double(b));
    return jk_int(jk_as_int(a) - jk_as_int(b));
}

static JKValue jk_mul(JKValue a, JKValue b)
{
    double factor, fen;
    if (a.tag == JK_RMB && b.tag == JK_RMB)
        jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe4\xba\xba\xe6\xb0\x91\xe5\xb8\x81\xe4\xb8\x8d\xe8\x83\xbd\xe4\xb9\x98\xe4\xba\xba\xe6\xb0\x91\xe5\xb8\x81");
    if (a.tag == JK_RMB || b.tag == JK_RMB) {
        long long base = (a.tag == JK_RMB) ? a.v.fen : b.v.fen;
        factor = (a.tag == JK_RMB) ? jk_as_double(b) : jk_as_double(a);
        fen = (double)base * factor;
        return jk_rmb((long long)(fen >= 0 ? floor(fen + 0.5) : -floor(-fen + 0.5)));
    }
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT)
        return jk_float(jk_as_double(a) * jk_as_double(b));
    return jk_int(jk_as_int(a) * jk_as_int(b));
}

static JKValue jk_div(JKValue a, JKValue b)
{
    double db, fen;
    if (a.tag == JK_RMB) {
        db = jk_as_double(b);
        if (db == 0.0) jk_fatal(JK_ERR_DIV0);
        fen = (double)a.v.fen / db;
        return jk_rmb((long long)(fen >= 0 ? floor(fen + 0.5) : -floor(-fen + 0.5)));
    }
    db = jk_as_double(b);
    if (db == 0.0) jk_fatal(JK_ERR_DIV0);
    return jk_float(jk_as_double(a) / db);   /* 真除法，与解释器一致 */
}

/* Python 的 % 取模：符号跟随除数 */
static JKValue jk_mod(JKValue a, JKValue b)
{
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT) {
        double x = jk_as_double(a), y = jk_as_double(b), m;
        if (y == 0.0) jk_fatal(JK_ERR_DIV0);
        m = fmod(x, y);
        if (m != 0.0 && ((m < 0) != (y < 0))) m += y;
        return jk_float(m);
    } else {
        long long x = jk_as_int(a), y = jk_as_int(b), m;
        if (y == 0) jk_fatal(JK_ERR_DIV0);
        m = x % y;
        if (m != 0 && ((m < 0) != (y < 0))) m += y;
        return jk_int(m);
    }
}

/* Python 的 // 整除：向下取整 */
static JKValue jk_floordiv(JKValue a, JKValue b)
{
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT) {
        double x = jk_as_double(a), y = jk_as_double(b);
        if (y == 0.0) jk_fatal(JK_ERR_DIV0);
        return jk_float(floor(x / y));
    } else {
        long long x = jk_as_int(a), y = jk_as_int(b), q;
        if (y == 0) jk_fatal(JK_ERR_DIV0);
        q = x / y;
        if ((x % y != 0) && ((x < 0) != (y < 0))) q -= 1;
        return jk_int(q);
    }
}

static JKValue jk_pow(JKValue a, JKValue b)
{
    /* Python: int ** 非负 int → int；其余 → float */
    if ((a.tag == JK_INT || a.tag == JK_BOOL) &&
        (b.tag == JK_INT || b.tag == JK_BOOL) && jk_as_int(b) >= 0) {
        long long base = jk_as_int(a), e = jk_as_int(b), r = 1;
        while (e > 0) {
            if (e & 1) r *= base;
            base *= base;
            e >>= 1;
        }
        return jk_int(r);
    }
    return jk_float(pow(jk_as_double(a), jk_as_double(b)));
}

static JKValue jk_neg(JKValue a)
{
    switch (a.tag) {
    case JK_INT:
    case JK_BOOL:  return jk_int(-jk_as_int(a));
    case JK_FLOAT: return jk_float(-a.v.d);
    case JK_RMB:   return jk_rmb(-a.v.fen);
    default:       jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe5\x8f\x96\xe8\xb4\x9f\xe9\x9c\x80\xe8\xa6\x81\xe6\x95\xb0\xe5\x80\xbc"); return jk_nil();
    }
}

static JKValue jk_abs(JKValue a)
{
    switch (a.tag) {
    case JK_INT:
    case JK_BOOL:  { long long x = jk_as_int(a); return jk_int(x < 0 ? -x : x); }
    case JK_FLOAT: return jk_float(fabs(a.v.d));
    case JK_RMB:   return jk_rmb(a.v.fen < 0 ? -a.v.fen : a.v.fen);
    default:       jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe7\xbb\x9d\xe5\xaf\xb9\xe5\x80\xbc\xe9\x9c\x80\xe8\xa6\x81\xe6\x95\xb0\xe5\x80\xbc"); return jk_nil();
    }
}

/* ---------- 比较 ---------- */

static int jk_cmp_eq(JKValue a, JKValue b)
{
    if (a.tag == JK_NIL || b.tag == JK_NIL)
        return a.tag == b.tag;
    if (a.tag == JK_STR || b.tag == JK_STR)
        return (a.tag == b.tag) && strcmp(a.v.s, b.v.s) == 0;
    if (a.tag == JK_RMB || b.tag == JK_RMB)
        return jk_to_fen(a) == jk_to_fen(b);
    if (a.tag == JK_BOOL && b.tag == JK_BOOL)
        return a.v.b == b.v.b;
    return jk_as_double(a) == jk_as_double(b);
}

static JKValue jk_eq(JKValue a, JKValue b) { return jk_bool(jk_cmp_eq(a, b)); }
static JKValue jk_ne(JKValue a, JKValue b) { return jk_bool(!jk_cmp_eq(a, b)); }

/* 返回 -1 / 0 / 1；类型不可比时直接停机（与解释器抛 TypeError 对齐） */
static int jk_cmp_ord(JKValue a, JKValue b)
{
    if (a.tag == JK_STR && b.tag == JK_STR) {
        int c = strcmp(a.v.s, b.v.s);
        return c < 0 ? -1 : (c > 0 ? 1 : 0);
    }
    if (a.tag == JK_STR || b.tag == JK_STR)
        jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe5\x8f\xaa\xe8\x83\xbd\xe4\xb8\x8e\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe6\xaf\x94\xe8\xbe\x83\xe5\xa4\xa7\xe5\xb0\x8f");
    if (a.tag == JK_RMB || b.tag == JK_RMB) {
        long long x = jk_to_fen(a), y = jk_to_fen(b);
        return x < y ? -1 : (x > y ? 1 : 0);
    }
    if (!jk_is_num(a) || !jk_is_num(b))
        jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe8\xaf\xa5\xe7\xb1\xbb\xe5\x9e\x8b\xe4\xb8\x8d\xe6\x94\xaf\xe6\x8c\x81\xe6\xaf\x94\xe8\xbe\x83\xe5\xa4\xa7\xe5\xb0\x8f");
    {
        double x = jk_as_double(a), y = jk_as_double(b);
        return x < y ? -1 : (x > y ? 1 : 0);
    }
}

static JKValue jk_gt(JKValue a, JKValue b) { return jk_bool(jk_cmp_ord(a, b) >  0); }
static JKValue jk_lt(JKValue a, JKValue b) { return jk_bool(jk_cmp_ord(a, b) <  0); }
static JKValue jk_ge(JKValue a, JKValue b) { return jk_bool(jk_cmp_ord(a, b) >= 0); }
static JKValue jk_le(JKValue a, JKValue b) { return jk_bool(jk_cmp_ord(a, b) <= 0); }

/* ---------- 逻辑 ----------
 * 注意：Python 的 and / or 返回操作数本身而不是布尔，解释器就是
 * a and b / a or b，这里必须照抄这个语义。
 */
static JKValue jk_and(JKValue a, JKValue b) { return jk_truthy(a) ? b : a; }
static JKValue jk_or(JKValue a, JKValue b)  { return jk_truthy(a) ? a : b; }
static JKValue jk_not(JKValue a)            { return jk_bool(!jk_truthy(a)); }

/* ---------- 控制台初始化 ---------- */

static void jk_init_console(void)
{
#ifdef _WIN32
    SetConsoleOutputCP(65001);   /* 让中文在 Windows 控制台正确显示 */
#endif
}

'''


# ---------------------------------------------------------------------------
# 生成器
# ---------------------------------------------------------------------------

class CCodegen:
    """把受支持子集的 AST 翻译为 C 源码。

    变量模型：AOT 子集没有控制流也没有函数，顶层就是一条直线语句序列，
    所以「所有变量都是 main() 的局部变量」这个最朴素的模型就够用。先扫一遍
    收集全部名字统一声明，再按语句序逐条赋值——这样重复「定义」同名变量不会
    撞 C 的重复声明。未定义就读取（前向引用）在直线代码里可以静态判死，因此
    codegen 直接抛 CodegenError，而不是生成读未初始化内存的 C。
    """

    def __init__(self) -> None:
        self._slots: Dict[str, str] = {}     # 极快变量名 → C 标识符
        self._defined: Set[str] = set()      # 已赋过值的名字（定值分析）
        self._lines: List[str] = []

    # ---- 入口 ----

    def generate(self, program: Program) -> str:
        self._slots.clear()
        self._defined.clear()
        self._lines = []

        self._collect_slots(program)

        decls = []
        for name in sorted(self._slots, key=lambda n: self._slots[n]):
            decls.append(
                "    JKValue {} = jk_nil();   /* {} */".format(self._slots[name], name)
            )

        for stmt in program.body:
            self._emit_stmt(stmt)

        parts = [_C_RUNTIME, "int main(void)\n{\n    jk_init_console();\n"]
        if decls:
            parts.append("\n".join(decls) + "\n\n")
        parts.append("\n".join(self._lines))
        parts.append("\n    return 0;\n}\n")
        return "".join(parts)

    # ---- 变量槽位 ----

    def _collect_slots(self, program: Program) -> None:
        """预扫顶层语句，给每个被定义/赋值的名字分配一个 C 标识符。

        极快标识符可以是中文，不能直接当 C 标识符，因此统一映射为 jk_varN，
        并在声明处用注释保留原名，方便读生成的 C。
        """
        for stmt in program.body:
            name = None
            if isinstance(stmt, Define):
                name = stmt.name
            elif isinstance(stmt, Assign) and isinstance(stmt.target, Ident):
                name = stmt.target.name
            if name is not None and name not in self._slots:
                self._slots[name] = "jk_var{}".format(len(self._slots) + 1)

    # ---- 语句 ----

    def _emit_stmt(self, node: Node) -> None:
        if isinstance(node, Define):
            expr = self._expr(node.value)
            self._defined.add(node.name)
            self._lines.append("    {} = {};".format(self._slot(node.name), expr))
            return

        if isinstance(node, Assign):
            target = node.target
            if not isinstance(target, Ident):
                raise CodegenError(
                    "赋值目标必须是变量名，收到 {}".format(type(target).__name__)
                )
            expr = self._expr(node.value)
            self._defined.add(target.name)
            self._lines.append("    {} = {};".format(self._slot(target.name), expr))
            return

        if isinstance(node, Call) and node.verb == "打印":
            self._emit_print(node)
            return

        if isinstance(node, Call):
            # 顶层裸表达式：求值后丢弃（保留可能的副作用，如除零停机）
            self._lines.append("    (void)({});".format(self._expr(node)))
            return

        raise CodegenError("AOT 不支持的顶层语句：{}".format(type(node).__name__))

    def _emit_print(self, node: Call) -> None:
        """打印是变参：多参数用空格分隔，末尾换行（与解释器 print(*args) 一致）。"""
        if not node.args:
            self._lines.append("    jk_print(0, NULL);")
            return
        args = [self._expr(a) for a in node.args]
        tmp = "jk_args{}".format(len(self._lines) + 1)
        self._lines.append(
            "    {{ JKValue {}[] = {{ {} }}; jk_print({}, {}); }}".format(
                tmp, ", ".join(args), len(args), tmp
            )
        )

    # ---- 表达式 ----

    def _expr(self, node: Node) -> str:
        if isinstance(node, NumberLit):
            value = node.value
            if isinstance(value, bool):
                return "jk_bool({})".format(1 if value else 0)
            if isinstance(value, int):
                return "jk_int({}LL)".format(value)
            return "jk_float({})".format(_c_double(float(value)))

        if isinstance(node, MoneyLit):
            return "jk_rmb({}LL)".format(_to_fen(node.value))

        if isinstance(node, StringLit):
            return 'jk_str("{}")'.format(_c_escape(node.value))

        if isinstance(node, BoolLit):
            return "jk_bool({})".format(1 if node.value else 0)

        if isinstance(node, NilLit):
            return "jk_nil()"

        if isinstance(node, Ident):
            if node.name not in self._defined:
                raise CodegenError(
                    "未定义的名称：{}（AOT 不支持前向引用，请先用「定义」赋值）"
                    .format(node.name)
                )
            return self._slot(node.name)

        if isinstance(node, Call):
            return self._call(node)

        raise CodegenError("AOT 不支持的表达式：{}".format(type(node).__name__))

    def _call(self, node: Call) -> str:
        verb = node.verb

        if verb == "打印":
            raise CodegenError("「打印」只能作为语句使用，不能当表达式取值")

        if verb in _UNARY_OPS:
            if len(node.args) != 1:
                raise CodegenError(
                    "动词 {} 需要 1 个参数，收到 {}".format(verb, len(node.args))
                )
            return "{}({})".format(_UNARY_OPS[verb], self._expr(node.args[0]))

        if verb in _BINARY_OPS:
            if len(node.args) != 2:
                raise CodegenError(
                    "动词 {} 需要 2 个参数，收到 {}".format(verb, len(node.args))
                )
            return "{}({}, {})".format(
                _BINARY_OPS[verb],
                self._expr(node.args[0]),
                self._expr(node.args[1]),
            )

        raise CodegenError("AOT 不支持的内建动词：{}".format(verb))

    # ---- 工具 ----

    def _slot(self, name: str) -> str:
        slot = self._slots.get(name)
        if slot is None:
            raise CodegenError("内部错误：变量 {} 未分配槽位".format(name))
        return slot


# ---------------------------------------------------------------------------
# 字面量转换
# ---------------------------------------------------------------------------

_CENT = Decimal("0.01")


def _to_fen(value) -> int:
    """元 → 分。在 Python 侧用 Decimal 精确换算，保证字面量零误差。

    与 evaluator.RMB._quantize 同口径：先经 str 进 Decimal（避开 float 的
    二进制表示误差），再 ROUND_HALF_UP 量化到分。
    """
    dec = value if isinstance(value, Decimal) else Decimal(str(value))
    return int(dec.quantize(_CENT, rounding=ROUND_HALF_UP) * 100)


def _c_double(value: float) -> str:
    """输出 C 能精确还原的 double 字面量（repr 给最短往返表示）。"""
    if value != value:
        return "(0.0/0.0)"
    if value == float("inf"):
        return "(1.0/0.0)"
    if value == float("-inf"):
        return "(-1.0/0.0)"
    text = repr(value)
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text


def _c_escape(text: str) -> str:
    """把 Python str 转成 C 字符串字面量内容。

    非 ASCII 一律按 UTF-8 编码后逐字节转成八位十六进制转义（前导反斜杠 x），
    这样生成的 C 不依赖编译器的源字符集设置，gcc -std=c11 与 MSVC 行为一致。
    转义序列后紧跟十六进制字符会被 C 贪婪吞掉，所以每个字节转义后主动断开
    字符串，交由 C 的相邻字面量拼接规则合并。
    """
    out: List[str] = []
    simple = {
        "\\": "\\\\",
        '"': '\\"',
        "\n": "\\n",
        "\r": "\\r",
        "\t": "\\t",
        "\a": "\\a",
        "\b": "\\b",
        "\f": "\\f",
        "\v": "\\v",
        "\0": "\\0",
    }
    for ch in text:
        if ch in simple:
            out.append(simple[ch])
        elif " " <= ch <= "~":
            out.append(ch)
        else:
            for byte in ch.encode("utf-8"):
                out.append('\\x{:02x}" "'.format(byte))
    return "".join(out)


# ---------------------------------------------------------------------------
# 对外接口
# ---------------------------------------------------------------------------

def generate_c(program: Program) -> str:
    """AST → 完整 C 源码字符串。

    调用方**必须**先跑 subset_gate.check 并确认返回 True。
    """
    return CCodegen().generate(program)