# -*- coding: utf-8 -*-
"""极快 AOT · C 中间码生成器（T-M6-A02 · ADR-19）。

把**已通过 subset_gate.check** 的 AST 翻译成可被 gcc -std=c11 编译的 C 源码。
调用方有义务先过门禁；本模块对子集外节点一律抛 CodegenError，而不是「尽力
翻译」——静默产出语义不对的产物比报错糟糕得多。

类型策略（动态 → 静态的降级方案）
--------------------------------
极快是动态类型，C 是静态类型。第一版用 tagged union（见 _C_RUNTIME 里的
JKValue）：所有运算走运行时辅助函数（jk_add / jk_lt / ...），在函数内部按
tag 分派，相当于把解释器的动态派发下沉到 C 层。代价是拿不到静态类型特化的
性能上限，收益是语义与解释器一致、实现量小、可审计。

人民币精度（ADR-19 硬要求）
--------------------------
**绝不用 double 存金额。** JK_RMB 用 long long 存「分」：￥99.90 → 9990。
字面量的「元 → 分」换算在 Python 侧用 Decimal 精确完成，所以字面量零误差。
只有运行时「金额 × 浮点因子」这类混算才会退化到 double 中转，该边界写进了
docs/AOT.md 局限清单。

中文字符串
----------
C 源码里直接写 UTF-8 字节转义（反斜杠 x 加两位十六进制），不依赖编译器的
源字符集推断。Windows 下 main() 开头调用 SetConsoleOutputCP(65001)，保证
控制台按 UTF-8 渲染；重定向到管道/文件时本来就是原始字节，不受影响。

浮点打印
--------
解释器用 Python 的 str(float)，即最短往返表示（repr）。C 的 %g 没有这个
语义，所以运行时用「精度 1..17 逐级尝试 + strtod 往返校验」复现它，并对
整数值浮点补 .0（Python 打印 3.0 而非 3）。
"""

from __future__ import annotations

import re
from decimal import ROUND_HALF_UP, Decimal
from typing import Dict, List, Optional

from jikuai.ast_nodes import (
    Assign,
    BoolLit,
    Break,
    Call,
    Continue,
    Define,
    DictLit,
    For,
    FuncCall,
    FuncDef,
    Ident,
    If,
    Index,
    ListLit,
    MoneyLit,
    NilLit,
    Node,
    NumberLit,
    Program,
    Repeat,
    Return,
    StringLit,
    While,
)


from .subset_gate import RANGE_ARITY, RANGE_VERB, SUPPORTED_VERBS


class CodegenError(Exception):
    """codegen 拒绝翻译。正常流程下不该触发——应先被 subset_gate 拦住。"""


# ---------------------------------------------------------------------------
# 动词 → 运行时函数名
# ---------------------------------------------------------------------------

#: 二元动词 → C 运行时函数。口语化别名与本名共用同一实现。
_BINARY_OPS: Dict[str, str] = {
    "加": "jk_add", "加上": "jk_add",
    "减": "jk_sub", "减去": "jk_sub",
    "乘": "jk_mul", "乘以": "jk_mul",
    "除": "jk_div", "除以": "jk_div",
    "取余": "jk_mod",
    "幂": "jk_pow",
    "整除": "jk_floordiv",
    "等于": "jk_eq",
    "不等于": "jk_ne",
    "大于": "jk_gt",
    "小于": "jk_lt",
    "大于等于": "jk_ge",
    "小于等于": "jk_le",
    "且": "jk_and",
    "或": "jk_or",
}

#: 一元动词 → C 运行时函数。
_UNARY_OPS: Dict[str, str] = {
    "负": "jk_neg",
    "绝对值": "jk_abs",
    "非": "jk_not",
}

# 自检：动词映射必须恰好覆盖受支持白名单（打印单独作为语句处理）。
assert set(_BINARY_OPS) | set(_UNARY_OPS) | {"打印"} == set(SUPPORTED_VERBS), (
    "codegen 动词映射与 subset_gate.SUPPORTED_VERBS 不一致"
)


# ---------------------------------------------------------------------------
# C 运行时（prelude）—— 原始字符串，内部反斜杠不被 Python 处理
# ---------------------------------------------------------------------------

_C_RUNTIME_HEAD = r'''/* ===========================================================
 * 极快 AOT 生成的 C 中间码 —— 自动生成，请勿手工编辑
 * Generated by jikuai_aot (Experimental, ADR-19)
 * =========================================================== */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdarg.h>

#ifdef _WIN32
#include <windows.h>
#endif

/* ---------- 值表示：tagged union ---------- */

enum JKTag {
    JK_NIL = 0,
    JK_INT = 1,
    JK_FLOAT = 2,
    JK_STR = 3,
    JK_BOOL = 4,
    JK_RMB = 5,     /* v.fen 存「分」，绝不用 double 存金额 */
    JK_LIST = 6,    /* v.obj 指向 JKList（ADR-37 §2.4） */
    JK_DICT = 7     /* v.obj 指向 JKDict（ADR-37 §2.4） */
};

typedef struct {
    int tag;
    union {
        long long i;
        double d;
        const char *s;
        int b;
        long long fen;
        void *obj;      /* JK_LIST → JKList *；JK_DICT → JKDict *（ADR-37 §2.4） */
    } v;
} JKValue;

static JKValue jk_nil(void)            { JKValue r; r.tag = JK_NIL;   r.v.i = 0;   return r; }
static JKValue jk_int(long long x)     { JKValue r; r.tag = JK_INT;   r.v.i = x;   return r; }
static JKValue jk_float(double x)      { JKValue r; r.tag = JK_FLOAT; r.v.d = x;   return r; }
static JKValue jk_str(const char *x)   { JKValue r; r.tag = JK_STR;   r.v.s = x;   return r; }
static JKValue jk_bool(int x)          { JKValue r; r.tag = JK_BOOL;  r.v.b = x ? 1 : 0; return r; }
static JKValue jk_rmb(long long fen)   { JKValue r; r.tag = JK_RMB;   r.v.fen = fen;     return r; }
static JKValue jk_list(void *p)        { JKValue r; r.tag = JK_LIST;  r.v.obj = p;       return r; }
static JKValue jk_dict(void *p)        { JKValue r; r.tag = JK_DICT;  r.v.obj = p;       return r; }

/* ---------- 堆容器（ADR-37 §2.2 / §2.4） ----------
 * **内存策略：malloc 之后全程不 free，进程退出时交给 OS 回收。**
 * 这是 ADR-37 §2.2 的明确决策（第一切片不做引用计数、也不做 GC），沿用
 * `jk_concat` 上方那段 arena 注释的口径 —— **不是**忘了写 free。
 *
 * 它之所以安全：第一切片的容器是「构造后只读」（下标写顺延，见 §2.3），
 * 而且门禁的 `循环体内构造容器` 规则挡住了循环内构造，因此一次运行里创建的
 * 容器个数由源码里的字面量个数静态封顶，进程又短命，内存有上界。
 *
 * 升级触发线（ADR-37 §4，任一命中即启动内存管理 ADR，届时凭度量选
 * refcount 还是 GC）：(a) 允许循环体内构造容器；(b) 容器可变操作进循环；
 * (c) 真实用例跑出 OOM。在此之前不碰。
 */

typedef struct {
    JKValue *items;
    long long len;
    long long cap;
} JKList;

/* 字典 = **有序 (键,值) 数组 + 线性查找**，不是哈希表。
 *
 * 为什么选它（ADR-37 §2.4 的要求是「元素少、进程短命，优先实现简单可审计的」）：
 *   1. 第一切片的字典全部来自字面量，条目数在编译期就写死在源码里，通常个位
 *      数。这个规模下线性扫描比哈希更快 —— 不用算哈希、不用处理冲突。
 *   2. 打印必须逐字复刻 Python 的 `str(dict)`，而 Python dict 保持**插入顺序**。
 *      有序数组天然满足；哈希表还得另挂一条顺序链才能做到。
 *   3. 键相等直接复用 `jk_cmp_eq` —— 与 `等于` 动词同一套语义。哈希表则要再写
 *      一个哈希函数，而「哈希与相等不一致」是哈希表最经典的隐蔽 bug 来源。
 *   4. 没有扩容 rehash 分支，整段可肉眼审计。
 * 代价：查找 O(n)。等到真有上千条目的字典时再换哈希表，届时另立 ADR。
 */
typedef struct {
    JKValue *keys;
    JKValue *vals;
    long long len;
    long long cap;
} JKDict;

/* ---------- 错误处理：与解释器一样「立刻停」 ---------- */

static void jk_fatal(const char *msg)
{
    fflush(stdout);
    fprintf(stderr, "%s\n", msg);
    exit(1);
}

/* ---------- 类型判定与取值 ---------- */

static int jk_is_num(JKValue a)
{
    return a.tag == JK_INT || a.tag == JK_FLOAT || a.tag == JK_BOOL;
}


static long long jk_as_int(JKValue a)
{
    switch (a.tag) {
    case JK_INT:   return a.v.i;
    case JK_BOOL:  return (long long)a.v.b;
    case JK_FLOAT: return (long long)a.v.d;
    default:       jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe9\x9c\x80\xe8\xa6\x81\xe6\x95\xb4\xe6\x95\xb0"); return 0;
    }
}

static double jk_as_double(JKValue a)
{
    switch (a.tag) {
    case JK_INT:   return (double)a.v.i;
    case JK_BOOL:  return (double)a.v.b;
    case JK_FLOAT: return a.v.d;
    case JK_RMB:   return (double)a.v.fen / 100.0;
    default:       jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe9\x9c\x80\xe8\xa6\x81\xe6\x95\xb0\xe5\x80\xbc"); return 0.0;
    }
}

/* 数值 → 分，四舍五入（ROUND_HALF_UP，与中国会计惯例一致） */
static long long jk_to_fen(JKValue a)
{
    double x;
    if (a.tag == JK_RMB) return a.v.fen;
    x = jk_as_double(a) * 100.0;
    return (long long)(x >= 0 ? floor(x + 0.5) : -floor(-x + 0.5));
}

/* Python 真值语义：空 / 假 / 0 / 0.0 / "" / 空容器 为假；人民币对象恒为真 */
static int jk_truthy(JKValue a)
{
    switch (a.tag) {
    case JK_NIL:   return 0;
    case JK_INT:   return a.v.i != 0;
    case JK_BOOL:  return a.v.b != 0;
    case JK_FLOAT: return a.v.d != 0.0;
    case JK_STR:   return a.v.s != NULL && a.v.s[0] != '\0';
    case JK_RMB:   return 1;
    case JK_LIST:  return ((JKList *)a.v.obj)->len != 0;   /* 空列表为假（同 Python） */
    case JK_DICT:  return ((JKDict *)a.v.obj)->len != 0;   /* 空字典为假（同 Python） */
    default:       return 0;
    }
}


/* ---------- 字符串拼接 ----------
 * 设计取舍：AOT 子集是直线代码、进程短命，故拼接结果故意不释放
 * （arena 语义）。这条写进 docs/AOT.md 局限清单。
 */
static const char *jk_concat(const char *a, const char *b)
{
    size_t la = strlen(a), lb = strlen(b);
    char *r = (char *)malloc(la + lb + 1);
    if (r == NULL) jk_fatal("\xe5\x86\x85\xe5\xad\x98\xe4\xb8\x8d\xe8\xb6\xb3");
    memcpy(r, a, la);
    memcpy(r + la, b, lb);
    r[la + lb] = '\0';
    return r;
}

/* ---------- 浮点格式化：复现 Python str(float) 的最短往返表示 ---------- */

static void jk_fmt_double(double d, char *buf, size_t n)
{
    int p;
    size_t len;

    if (isnan(d)) { snprintf(buf, n, "nan"); return; }
    if (isinf(d)) { snprintf(buf, n, d < 0 ? "-inf" : "inf"); return; }

    for (p = 1; p <= 17; p++) {
        snprintf(buf, n, "%.*g", p, d);
        if (strtod(buf, NULL) == d) break;
    }
    /* Python 打印整数值浮点为 3.0，%g 给的是 3 */
    if (strpbrk(buf, ".eE") == NULL) {
        len = strlen(buf);
        if (len + 2 < n) {
            buf[len] = '.';
            buf[len + 1] = '0';
            buf[len + 2] = '\0';
        }
    }
}

'''


# ---------------------------------------------------------------------------
# C 运行时 · 容器段（W104 · ADR-37 第一切片）
# ---------------------------------------------------------------------------
#
# 这一段单独拿出来是因为里面有大量中文文案，必须经 `_c_escape` 转成 UTF-8
# 十六进制转义（与全文件同一约定：生成的 C 不依赖编译器源字符集）。模板里
# 写成 `$中文$` 的占位符由 `_c_expand` 机械替换 —— 好处是这段 C 读起来还是
# 中文，不用人肉核对一串 \xNN，也不会出现「手抄转义抄错一个字节」这种事故。
#
# 位置：夹在 `jk_fmt_double`（它要用）与 `jk_write`（要用它）之间。
_C_RUNTIME_CONTAINERS = r'''/* ---------- 前向声明（相等判定要被字典查找与 repr 递归调用） ---------- */

static int jk_cmp_eq(JKValue a, JKValue b);

static const char *JK_ERR_OOM = "$内存不足$";

/* ---------- 可增长字符串缓冲 ----------
 * 打印容器与拼接诊断文案都需要变长字符串。同样是 arena 语义：**不 free**
 * （ADR-37 §2.2 的决策，不是疏漏）。缓冲对象本身在栈上，只有字节数组在堆上。
 */

typedef struct { char *p; size_t len; size_t cap; } JKBuf;

static void jk_buf_init(JKBuf *b)
{
    b->cap = 64;
    b->len = 0;
    b->p = (char *)malloc(b->cap);
    if (b->p == NULL) jk_fatal(JK_ERR_OOM);
    b->p[0] = '\0';
}

static void jk_buf_reserve(JKBuf *b, size_t extra)
{
    size_t need = b->len + extra + 1;      /* +1 给结尾的 NUL */
    if (need <= b->cap) return;
    while (b->cap < need) b->cap *= 2;
    b->p = (char *)realloc(b->p, b->cap);
    if (b->p == NULL) jk_fatal(JK_ERR_OOM);
}

static void jk_buf_putc(JKBuf *b, char c)
{
    jk_buf_reserve(b, 1);
    b->p[b->len++] = c;
    b->p[b->len] = '\0';
}

static void jk_buf_puts(JKBuf *b, const char *s)
{
    size_t n = strlen(s);
    jk_buf_reserve(b, n);
    memcpy(b->p + b->len, s, n);
    b->len += n;
    b->p[b->len] = '\0';
}

static void jk_buf_ll(JKBuf *b, long long x)
{
    char tmp[32];
    snprintf(tmp, sizeof(tmp), "%lld", x);
    jk_buf_puts(b, tmp);
}

/* 金额渲染：与 jk_write 的 JK_RMB 分支同一套（全角￥ + 两位小数） */
static void jk_buf_rmb(JKBuf *b, long long fen)
{
    char tmp[64];
    if (fen < 0) { jk_buf_putc(b, '-'); fen = -fen; }
    snprintf(tmp, sizeof(tmp), "$￥$%lld.%02lld", fen / 100, fen % 100);
    jk_buf_puts(b, tmp);
}

/* ---------- 中文类型名（逐字对齐 evaluator._中文类型名 / _类型名） ----------
 * 注意 JK_RMB 返回的是 "RMB" 而不是中文 —— 这**不是笔误**：解释器的
 * `_中文类型名` 表里没有 RMB 这一项，`_类型名` 于是退回 Python 类名 `RMB`。
 * 要的是「与解释器逐字一致」，不是「看起来更像中文」。
 */
static const char *jk_typename(JKValue a)
{
    switch (a.tag) {
    case JK_NIL:   return "$空$";
    case JK_INT:   return "$整数$";
    case JK_FLOAT: return "$小数$";
    case JK_STR:   return "$字符串$";
    case JK_BOOL:  return "$布尔$";
    case JK_RMB:   return "$人民币$";
    case JK_LIST:  return "$列表$";
    case JK_DICT:  return "$字典$";
    default:       return "?";
    }
}

/* ---------- Python `repr` 复现 ----------
 * 为什么容器里的元素要走 repr 而不是 jk_write：解释器打印容器时走
 * `_format_value` → `str(v)`，而 Python 的 `str(list)` / `str(dict)` 对**元素**
 * 用的是 `repr()`。实测（v0.22.0 主干）：
 *     打印 【1，2，3】。      → [1, 2, 3]
 *     打印 {"甲"：1}。        → {'甲': 1}
 *     打印 【真，假，空】。   → [True, False, None]     ← 不是 真/假/空！
 *     打印 【1.5，￥9.90】。  → [1.5, ￥9.90]
 * 所以容器内是**单引号 + True/False/None**，容器外才是「无引号 + 真/假/空」。
 * 两套渲染必须分开，不能共用一个函数。
 */

/* Python `repr(str)`：默认单引号；串里含 ' 且不含 " 时改用双引号；
 * 否则用单引号并把 ' 转义。可打印字符（含 UTF-8 汉字）原样保留。 */
static void jk_buf_str_repr(JKBuf *b, const char *s)
{
    char quote = '\'';
    const unsigned char *p;
    char tmp[8];

    if (strchr(s, '\'') != NULL && strchr(s, '"') == NULL) quote = '"';

    jk_buf_putc(b, quote);
    for (p = (const unsigned char *)s; *p != '\0'; p++) {
        unsigned char c = *p;
        if (c == (unsigned char)quote) {
            jk_buf_putc(b, '\\');
            jk_buf_putc(b, (char)c);
        } else if (c == '\\') {
            jk_buf_puts(b, "\\\\");
        } else if (c == '\n') {
            jk_buf_puts(b, "\\n");
        } else if (c == '\r') {
            jk_buf_puts(b, "\\r");
        } else if (c == '\t') {
            jk_buf_puts(b, "\\t");
        } else if (c < 0x20 || c == 0x7f) {
            snprintf(tmp, sizeof(tmp), "\\x%02x", (unsigned int)c);
            jk_buf_puts(b, tmp);
        } else {
            jk_buf_putc(b, (char)c);
        }
    }
    jk_buf_putc(b, quote);
}

static void jk_buf_repr(JKBuf *b, JKValue a)
{
    char tmp[64];
    long long i;

    switch (a.tag) {
    case JK_NIL:   jk_buf_puts(b, "None"); return;
    case JK_BOOL:  jk_buf_puts(b, a.v.b ? "True" : "False"); return;
    case JK_INT:   jk_buf_ll(b, a.v.i); return;
    case JK_FLOAT: jk_fmt_double(a.v.d, tmp, sizeof(tmp)); jk_buf_puts(b, tmp); return;
    case JK_STR:   jk_buf_str_repr(b, a.v.s); return;
    case JK_RMB:   jk_buf_rmb(b, a.v.fen); return;
    case JK_LIST: {
        JKList *L = (JKList *)a.v.obj;
        jk_buf_putc(b, '[');
        for (i = 0; i < L->len; i++) {
            if (i > 0) jk_buf_puts(b, ", ");
            jk_buf_repr(b, L->items[i]);
        }
        jk_buf_putc(b, ']');
        return;
    }
    case JK_DICT: {
        JKDict *D = (JKDict *)a.v.obj;
        jk_buf_putc(b, '{');
        for (i = 0; i < D->len; i++) {
            if (i > 0) jk_buf_puts(b, ", ");
            jk_buf_repr(b, D->keys[i]);
            jk_buf_puts(b, ": ");
            jk_buf_repr(b, D->vals[i]);
        }
        jk_buf_putc(b, '}');
        return;
    }
    default:
        jk_buf_putc(b, '?');
        return;
    }
}

/* ---------- 诊断里回显一个值（逐字对齐 evaluator._值文本） ----------
 * 字符串用中文引号「」包（不是 repr 的单引号 —— ADR-09 不许诊断泄漏实现细节），
 * 空/真/假 分别写作 空/真/假，其余等价 Python 的 `str()`（容器的 str 即上面的 repr）。
 */
static void jk_buf_valtext(JKBuf *b, JKValue a)
{
    switch (a.tag) {
    case JK_STR:
        jk_buf_puts(b, "$「$");
        jk_buf_puts(b, a.v.s);
        jk_buf_puts(b, "$」$");
        return;
    case JK_NIL:  jk_buf_puts(b, "$空$"); return;
    case JK_BOOL: jk_buf_puts(b, a.v.b ? "$真$" : "$假$"); return;
    default:      jk_buf_repr(b, a); return;
    }
}

/* ---------- 列表构造 ----------
 * 用可变参数而不是「临时变量 + 逐元素赋值」，是为了让列表/字典字面量编译成
 * 一个**纯表达式**：`_expr` 的产物会被塞进 `while (jk_truthy(...))`、
 * `if (...)`、`for (...)` 的头部，那些位置插不进语句；而且循环条件每轮都要
 * 重新求值，先落语句再引用临时变量会把语义弄错。
 * 已知取舍：C 不规定函数实参的求值顺序，所以多个元素里有两个都会停机时，
 * 先报哪一条不确定 —— 与既有 `jk_print` 的数组初值列表同一性质。
 */
static JKValue jk_list_new(long long cap)
{
    JKList *L = (JKList *)malloc(sizeof(JKList));
    if (L == NULL) jk_fatal(JK_ERR_OOM);
    L->len = 0;
    L->cap = (cap > 0) ? cap : 1;    /* malloc(0) 的返回值由实现定义，绕开它 */
    L->items = (JKValue *)malloc(sizeof(JKValue) * (size_t)L->cap);
    if (L->items == NULL) jk_fatal(JK_ERR_OOM);
    return jk_list(L);
}

static JKValue jk_list_of(int n, ...)
{
    va_list ap;
    int i;
    JKValue r = jk_list_new((long long)n);
    JKList *L = (JKList *)r.v.obj;

    va_start(ap, n);
    for (i = 0; i < n; i++) L->items[L->len++] = va_arg(ap, JKValue);
    va_end(ap);
    return r;
}

/* ---------- 字典构造 ---------- */

static JKValue jk_dict_new(long long cap)
{
    JKDict *D = (JKDict *)malloc(sizeof(JKDict));
    if (D == NULL) jk_fatal(JK_ERR_OOM);
    D->len = 0;
    D->cap = (cap > 0) ? cap : 1;
    D->keys = (JKValue *)malloc(sizeof(JKValue) * (size_t)D->cap);
    D->vals = (JKValue *)malloc(sizeof(JKValue) * (size_t)D->cap);
    if (D->keys == NULL || D->vals == NULL) jk_fatal(JK_ERR_OOM);
    return jk_dict(D);
}

/* 键限标量（ADR-37 §2.4）。字面量形态的容器键已被门禁的 `容器作字典键` 规则
 * 挡在编译期；这里兜住「变量里正好装着一个容器」的运行期形态，文案逐字对齐
 * 解释器 `_eval_DictLit` 的 ADR-23b 检查（那条文案里的 list/dict 是解释器现状，
 * 见交付报告里记的一条实现反馈）。
 *
 * 重复键：覆盖值、保留**首次插入位置** —— 复刻 Python dict 的行为，打印顺序
 * 才能与解释器一致。 */
static void jk_dict_set(JKValue dv, JKValue key, JKValue val)
{
    JKDict *D = (JKDict *)dv.v.obj;
    long long i;

    if (key.tag == JK_LIST || key.tag == JK_DICT) {
        JKBuf b;
        jk_buf_init(&b);
        jk_buf_puts(&b, "$字典的键必须是不可变类型（字符串/数字/布尔/空），当前键的类型是 $");
        jk_buf_puts(&b, (key.tag == JK_LIST) ? "list" : "dict");
        jk_fatal(b.p);
    }
    for (i = 0; i < D->len; i++) {
        if (jk_cmp_eq(D->keys[i], key)) { D->vals[i] = val; return; }
    }
    if (D->len == D->cap) {
        D->cap *= 2;
        D->keys = (JKValue *)realloc(D->keys, sizeof(JKValue) * (size_t)D->cap);
        D->vals = (JKValue *)realloc(D->vals, sizeof(JKValue) * (size_t)D->cap);
        if (D->keys == NULL || D->vals == NULL) jk_fatal(JK_ERR_OOM);
    }
    D->keys[D->len] = key;
    D->vals[D->len] = val;
    D->len++;
}

static JKValue jk_dict_of(int npairs, ...)
{
    va_list ap;
    int i;
    JKValue r = jk_dict_new((long long)npairs);

    va_start(ap, npairs);
    for (i = 0; i < npairs; i++) {
        JKValue k = va_arg(ap, JKValue);
        JKValue v = va_arg(ap, JKValue);
        jk_dict_set(r, k, v);
    }
    va_end(ap);
    return r;
}

/* ---------- 字符串下标：按**字符**（码位）而不是字节 ----------
 * 解释器里 `"你好"[1]` 是 好、`长度 "你好"` 是 2，所以 AOT 也必须按码位算。
 * UTF-8 续字节形如 10xxxxxx，数「非续字节」即得字符数。
 */
static long long jk_utf8_len(const char *s)
{
    long long n = 0;
    const unsigned char *p;
    for (p = (const unsigned char *)s; *p != '\0'; p++)
        if ((*p & 0xC0) != 0x80) n++;
    return n;
}

/* 取第 index 个字符（0-based，调用方保证已过越界检查），返回新分配的单字符串。 */
static const char *jk_utf8_char(const char *s, long long index)
{
    const unsigned char *p = (const unsigned char *)s;
    const unsigned char *start;
    long long n = -1;
    size_t width;
    char *out;

    for (; *p != '\0'; p++) {
        if ((*p & 0xC0) != 0x80) {
            n++;
            if (n == index) break;
        }
    }
    start = p;
    if (*p != '\0') p++;
    while (*p != '\0' && (*p & 0xC0) == 0x80) p++;
    width = (size_t)(p - start);
    out = (char *)malloc(width + 1);
    if (out == NULL) jk_fatal(JK_ERR_OOM);
    memcpy(out, start, width);
    out[width] = '\0';
    return out;
}

/* ---------- 下标读（ADR-37 §2.3：只读，写顺延） ----------
 * 分支顺序与错误文案逐字复刻解释器 `_eval_Index`（ADR-37 §2.5 要求「先修
 * 解释器再对齐」，文案的唯一定义处在 evaluator.py，这里只是搬运）：
 *     1. 字典缺键        → 键不存在：字典里没有键 X
 *     2. 容器当字典键    → {中文类型名}不能作为字典的键（键必须是字符串/数字/布尔/空）
 *     3. 序列下标越界    → 下标越界：{中文类型名}长度为 N，下标 I 超出有效范围（-N 到 N-1）
 *     4. 序列下标非数字  → 下标必须是整数，收到{中文类型名} {值文本}
 *     5. 对标量取下标    → {中文类型名}不支持下标取值
 *
 * 两条**故意保留**的现状语义（ADR-37 §2.5/§4，明令不许「顺手改对」）：
 *     - 负下标按尾部计数：`赵表[-1]` 是最后一个，不报错；
 *     - 小数下标截断：`赵表[1.7]` 取下标 1，不报错也不提示。
 */
static JKValue jk_index(JKValue obj, JKValue idx)
{
    JKBuf b;
    long long i, len;

    /* 字典按键取值（键**不**强转整数） */
    if (obj.tag == JK_DICT) {
        JKDict *D = (JKDict *)obj.v.obj;
        if (idx.tag == JK_LIST || idx.tag == JK_DICT) {
            jk_buf_init(&b);
            jk_buf_puts(&b, jk_typename(idx));
            jk_buf_puts(&b, "$不能作为字典的键（键必须是字符串/数字/布尔/空）$");
            jk_fatal(b.p);
        }
        for (i = 0; i < D->len; i++)
            if (jk_cmp_eq(D->keys[i], idx)) return D->vals[i];
        jk_buf_init(&b);
        jk_buf_puts(&b, "$键不存在：字典里没有键 $");
        jk_buf_valtext(&b, idx);
        jk_fatal(b.p);
        return jk_nil();                 /* 不可达：jk_fatal 里 exit(1) */
    }

    /* 序列（列表 / 字符串）按整数下标取值 */
    if (obj.tag == JK_LIST || obj.tag == JK_STR) {
        /* 下标必须是数字。布尔是整数的子类型，与解释器一样天然放行。 */
        if (idx.tag != JK_INT && idx.tag != JK_FLOAT && idx.tag != JK_BOOL) {
            jk_buf_init(&b);
            jk_buf_puts(&b, "$下标必须是整数，收到$");
            jk_buf_puts(&b, jk_typename(idx));
            jk_buf_putc(&b, ' ');
            jk_buf_valtext(&b, idx);
            jk_fatal(b.p);
        }
        i = jk_as_int(idx);              /* 小数在这里被截断（ADR-37 §2.5 现状语义） */
        len = (obj.tag == JK_LIST) ? ((JKList *)obj.v.obj)->len
                                   : jk_utf8_len(obj.v.s);
        if (i < -len || i >= len) {
            jk_buf_init(&b);
            jk_buf_puts(&b, "$下标越界：$");
            jk_buf_puts(&b, jk_typename(obj));
            jk_buf_puts(&b, "$长度为 $");
            jk_buf_ll(&b, len);
            jk_buf_puts(&b, "$，下标 $");
            jk_buf_ll(&b, i);
            jk_buf_puts(&b, "$ 超出有效范围（$");
            jk_buf_ll(&b, -len);
            jk_buf_puts(&b, "$ 到 $");
            jk_buf_ll(&b, len - 1);
            jk_buf_puts(&b, "$）$");
            jk_fatal(b.p);
        }
        if (i < 0) i += len;             /* 负下标按尾部计数（ADR-37 §2.5 现状语义） */
        if (obj.tag == JK_LIST) return ((JKList *)obj.v.obj)->items[i];
        return jk_str(jk_utf8_char(obj.v.s, i));
    }

    /* 其余类型（整数/小数/布尔/空/人民币）不支持下标 */
    jk_buf_init(&b);
    jk_buf_puts(&b, jk_typename(obj));
    jk_buf_puts(&b, "$不支持下标取值$");
    jk_fatal(b.p);
    return jk_nil();                     /* 不可达 */
}

'''

_C_RUNTIME_TAIL = r'''/* ---------- 打印 ---------- */


static void jk_write(JKValue a)
{
    char buf[64];
    long long fen, yuan, cents;

    switch (a.tag) {
    case JK_NIL:
        fputs("\xe7\xa9\xba", stdout);                  /* 空 */
        break;
    case JK_INT:
        printf("%lld", a.v.i);
        break;
    case JK_BOOL:
        fputs(a.v.b ? "\xe7\x9c\x9f" : "\xe5\x81\x87", stdout);  /* 真 / 假 */
        break;
    case JK_FLOAT:
        jk_fmt_double(a.v.d, buf, sizeof(buf));
        fputs(buf, stdout);
        break;
    case JK_STR:
        fputs(a.v.s, stdout);
        break;
    case JK_RMB:
        fen = a.v.fen;
        if (fen < 0) { fputs("-", stdout); fen = -fen; }
        yuan = fen / 100;
        cents = fen % 100;
        printf("\xef\xbf\xa5%lld.%02lld", yuan, cents); /* 全角￥ */
        break;
    case JK_LIST:
    case JK_DICT: {
        /* 容器走 Python 的 `str(list)` / `str(dict)`：外壳是 [] / {}，
         * 元素用 **repr**（单引号字符串、True/False/None）。见 jk_buf_repr
         * 上方那段实测记录 —— 容器内外是两套渲染，不能共用。 */
        JKBuf b;
        jk_buf_init(&b);
        jk_buf_repr(&b, a);
        fputs(b.p, stdout);
        break;
    }
    default:
        jk_fatal("\xe5\x86\x85\xe9\x83\xa8\xe9\x94\x99\xe8\xaf\xaf");
    }
}


static void jk_print(int argc, JKValue *argv)
{
    int i;
    for (i = 0; i < argc; i++) {
        if (i > 0) fputs(" ", stdout);
        jk_write(argv[i]);
    }
    fputs("\n", stdout);
}

/* ---------- 算术 ---------- */

static const char *JK_ERR_DIV0 = "\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe9\x99\xa4\xe6\x95\xb0\xe4\xb8\x8d\xe8\x83\xbd\xe4\xb8\xba\xe9\x9b\xb6";

static JKValue jk_add(JKValue a, JKValue b)
{
    if (a.tag == JK_STR && b.tag == JK_STR)
        return jk_str(jk_concat(a.v.s, b.v.s));
    if (a.tag == JK_STR || b.tag == JK_STR)
        jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe5\x8f\xaa\xe8\x83\xbd\xe4\xb8\x8e\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe7\x9b\xb8\xe5\x8a\xa0");
    /* 解释器里 `加 列表甲 列表乙` 是列表拼接（Python 的 list + list）。
     * 第一切片**不做**容器算术：拼接要新分配、而分配就绕回 §2.2 的内存决策。
     * 显式停机而不是让它掉进 jk_as_int 报「需要整数」—— 后者会让用户以为
     * 自己写错了类型，而实际是 AOT 暂不支持。已记入 docs/AOT.md 局限清单。 */
    if (a.tag == JK_LIST || b.tag == JK_LIST || a.tag == JK_DICT || b.tag == JK_DICT)
        jk_fatal("$类型错误：AOT 第一切片不支持容器参与算术（列表拼接等顺延，见 ADR-37 §4）$");
    if (a.tag == JK_RMB || b.tag == JK_RMB)
        return jk_rmb(jk_to_fen(a) + jk_to_fen(b));
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT)
        return jk_float(jk_as_double(a) + jk_as_double(b));
    return jk_int(jk_as_int(a) + jk_as_int(b));
}


static JKValue jk_sub(JKValue a, JKValue b)
{
    if (a.tag == JK_RMB || b.tag == JK_RMB)
        return jk_rmb(jk_to_fen(a) - jk_to_fen(b));
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT)
        return jk_float(jk_as_double(a) - jk_as_double(b));
    return jk_int(jk_as_int(a) - jk_as_int(b));
}

static JKValue jk_mul(JKValue a, JKValue b)
{
    double factor, fen;
    if (a.tag == JK_RMB && b.tag == JK_RMB)
        jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe4\xba\xba\xe6\xb0\x91\xe5\xb8\x81\xe4\xb8\x8d\xe8\x83\xbd\xe4\xb9\x98\xe4\xba\xba\xe6\xb0\x91\xe5\xb8\x81");
    if (a.tag == JK_RMB || b.tag == JK_RMB) {
        long long base = (a.tag == JK_RMB) ? a.v.fen : b.v.fen;
        factor = (a.tag == JK_RMB) ? jk_as_double(b) : jk_as_double(a);
        fen = (double)base * factor;
        return jk_rmb((long long)(fen >= 0 ? floor(fen + 0.5) : -floor(-fen + 0.5)));
    }
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT)
        return jk_float(jk_as_double(a) * jk_as_double(b));
    return jk_int(jk_as_int(a) * jk_as_int(b));
}

static JKValue jk_div(JKValue a, JKValue b)
{
    double db, fen;
    if (a.tag == JK_RMB) {
        db = jk_as_double(b);
        if (db == 0.0) jk_fatal(JK_ERR_DIV0);
        fen = (double)a.v.fen / db;
        return jk_rmb((long long)(fen >= 0 ? floor(fen + 0.5) : -floor(-fen + 0.5)));
    }
    db = jk_as_double(b);
    if (db == 0.0) jk_fatal(JK_ERR_DIV0);
    return jk_float(jk_as_double(a) / db);   /* 真除法，与解释器一致 */
}

/* Python 的 % 取模：符号跟随除数 */
static JKValue jk_mod(JKValue a, JKValue b)
{
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT) {
        double x = jk_as_double(a), y = jk_as_double(b), m;
        if (y == 0.0) jk_fatal(JK_ERR_DIV0);
        m = fmod(x, y);
        if (m != 0.0 && ((m < 0) != (y < 0))) m += y;
        return jk_float(m);
    } else {
        long long x = jk_as_int(a), y = jk_as_int(b), m;
        if (y == 0) jk_fatal(JK_ERR_DIV0);
        m = x % y;
        if (m != 0 && ((m < 0) != (y < 0))) m += y;
        return jk_int(m);
    }
}

/* Python 的 // 整除：向下取整 */
static JKValue jk_floordiv(JKValue a, JKValue b)
{
    if (a.tag == JK_FLOAT || b.tag == JK_FLOAT) {
        double x = jk_as_double(a), y = jk_as_double(b);
        if (y == 0.0) jk_fatal(JK_ERR_DIV0);
        return jk_float(floor(x / y));
    } else {
        long long x = jk_as_int(a), y = jk_as_int(b), q;
        if (y == 0) jk_fatal(JK_ERR_DIV0);
        q = x / y;
        if ((x % y != 0) && ((x < 0) != (y < 0))) q -= 1;
        return jk_int(q);
    }
}

static JKValue jk_pow(JKValue a, JKValue b)
{
    /* Python: int ** 非负 int → int；其余 → float */
    if ((a.tag == JK_INT || a.tag == JK_BOOL) &&
        (b.tag == JK_INT || b.tag == JK_BOOL) && jk_as_int(b) >= 0) {
        long long base = jk_as_int(a), e = jk_as_int(b), r = 1;
        while (e > 0) {
            if (e & 1) r *= base;
            base *= base;
            e >>= 1;
        }
        return jk_int(r);
    }
    return jk_float(pow(jk_as_double(a), jk_as_double(b)));
}

static JKValue jk_neg(JKValue a)
{
    switch (a.tag) {
    case JK_INT:
    case JK_BOOL:  return jk_int(-jk_as_int(a));
    case JK_FLOAT: return jk_float(-a.v.d);
    case JK_RMB:   return jk_rmb(-a.v.fen);
    default:       jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe5\x8f\x96\xe8\xb4\x9f\xe9\x9c\x80\xe8\xa6\x81\xe6\x95\xb0\xe5\x80\xbc"); return jk_nil();
    }
}

static JKValue jk_abs(JKValue a)
{
    switch (a.tag) {
    case JK_INT:
    case JK_BOOL:  { long long x = jk_as_int(a); return jk_int(x < 0 ? -x : x); }
    case JK_FLOAT: return jk_float(fabs(a.v.d));
    case JK_RMB:   return jk_rmb(a.v.fen < 0 ? -a.v.fen : a.v.fen);
    default:       jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe7\xbb\x9d\xe5\xaf\xb9\xe5\x80\xbc\xe9\x9c\x80\xe8\xa6\x81\xe6\x95\xb0\xe5\x80\xbc"); return jk_nil();
    }
}

/* ---------- 比较 ---------- */

static int jk_cmp_eq(JKValue a, JKValue b)
{
    /* 容器结构相等（复刻 Python）：列表按序逐元素比，字典与顺序无关。
     * 必须在标量分支**之前**，否则 jk_as_double 会拿容器去当数值。
     * 这一条也是字典查找的键相等判据 —— 相等只定义一次，避免「哈希与相等
     * 不一致」这类经典 bug（见 JKDict 上方的选型注释）。 */
    if (a.tag == JK_LIST || b.tag == JK_LIST) {
        JKList *x, *y;
        long long i;
        if (a.tag != JK_LIST || b.tag != JK_LIST) return 0;
        x = (JKList *)a.v.obj;
        y = (JKList *)b.v.obj;
        if (x->len != y->len) return 0;
        for (i = 0; i < x->len; i++)
            if (!jk_cmp_eq(x->items[i], y->items[i])) return 0;
        return 1;
    }
    if (a.tag == JK_DICT || b.tag == JK_DICT) {
        JKDict *x, *y;
        long long i, j;
        int found;
        if (a.tag != JK_DICT || b.tag != JK_DICT) return 0;
        x = (JKDict *)a.v.obj;
        y = (JKDict *)b.v.obj;
        if (x->len != y->len) return 0;
        for (i = 0; i < x->len; i++) {
            found = 0;
            for (j = 0; j < y->len; j++) {
                if (jk_cmp_eq(x->keys[i], y->keys[j])) {
                    if (!jk_cmp_eq(x->vals[i], y->vals[j])) return 0;
                    found = 1;
                    break;
                }
            }
            if (!found) return 0;
        }
        return 1;
    }
    if (a.tag == JK_NIL || b.tag == JK_NIL)
        return a.tag == b.tag;
    if (a.tag == JK_STR || b.tag == JK_STR)
        return (a.tag == b.tag) && strcmp(a.v.s, b.v.s) == 0;
    if (a.tag == JK_RMB || b.tag == JK_RMB)
        return jk_to_fen(a) == jk_to_fen(b);
    if (a.tag == JK_BOOL && b.tag == JK_BOOL)
        return a.v.b == b.v.b;
    return jk_as_double(a) == jk_as_double(b);
}


static JKValue jk_eq(JKValue a, JKValue b) { return jk_bool(jk_cmp_eq(a, b)); }
static JKValue jk_ne(JKValue a, JKValue b) { return jk_bool(!jk_cmp_eq(a, b)); }

/* 返回 -1 / 0 / 1；类型不可比时直接停机（与解释器抛 TypeError 对齐） */
static int jk_cmp_ord(JKValue a, JKValue b)
{
    /* 列表按字典序比较（复刻 Python：逐元素比，全等则比长度）。
     * 字典**不**参与大小比较 —— Python 里 `{} < {}` 也是 TypeError，
     * 所以让它落到下面 `!jk_is_num` 那条既有的停机分支即可。 */
    if (a.tag == JK_LIST && b.tag == JK_LIST) {
        JKList *x = (JKList *)a.v.obj;
        JKList *y = (JKList *)b.v.obj;
        long long n = (x->len < y->len) ? x->len : y->len;
        long long i;
        for (i = 0; i < n; i++)
            if (!jk_cmp_eq(x->items[i], y->items[i]))
                return jk_cmp_ord(x->items[i], y->items[i]);
        return (x->len < y->len) ? -1 : ((x->len > y->len) ? 1 : 0);
    }
    if (a.tag == JK_STR && b.tag == JK_STR) {

        int c = strcmp(a.v.s, b.v.s);
        return c < 0 ? -1 : (c > 0 ? 1 : 0);
    }
    if (a.tag == JK_STR || b.tag == JK_STR)
        jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe5\x8f\xaa\xe8\x83\xbd\xe4\xb8\x8e\xe5\xad\x97\xe7\xac\xa6\xe4\xb8\xb2\xe6\xaf\x94\xe8\xbe\x83\xe5\xa4\xa7\xe5\xb0\x8f");
    if (a.tag == JK_RMB || b.tag == JK_RMB) {
        long long x = jk_to_fen(a), y = jk_to_fen(b);
        return x < y ? -1 : (x > y ? 1 : 0);
    }
    if (!jk_is_num(a) || !jk_is_num(b))
        jk_fatal("\xe7\xb1\xbb\xe5\x9e\x8b\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x9a\xe8\xaf\xa5\xe7\xb1\xbb\xe5\x9e\x8b\xe4\xb8\x8d\xe6\x94\xaf\xe6\x8c\x81\xe6\xaf\x94\xe8\xbe\x83\xe5\xa4\xa7\xe5\xb0\x8f");
    {
        double x = jk_as_double(a), y = jk_as_double(b);
        return x < y ? -1 : (x > y ? 1 : 0);
    }
}

static JKValue jk_gt(JKValue a, JKValue b) { return jk_bool(jk_cmp_ord(a, b) >  0); }
static JKValue jk_lt(JKValue a, JKValue b) { return jk_bool(jk_cmp_ord(a, b) <  0); }
static JKValue jk_ge(JKValue a, JKValue b) { return jk_bool(jk_cmp_ord(a, b) >= 0); }
static JKValue jk_le(JKValue a, JKValue b) { return jk_bool(jk_cmp_ord(a, b) <= 0); }

/* ---------- 逻辑 ----------
 * 注意：Python 的 and / or 返回操作数本身而不是布尔，解释器就是
 * a and b / a or b，这里必须照抄这个语义。
 */
static JKValue jk_and(JKValue a, JKValue b) { return jk_truthy(a) ? b : a; }
static JKValue jk_or(JKValue a, JKValue b)  { return jk_truthy(a) ? a : b; }
static JKValue jk_not(JKValue a)            { return jk_bool(!jk_truthy(a)); }

/* ---------- 控制台初始化 ---------- */

static void jk_init_console(void)
{
#ifdef _WIN32
    SetConsoleOutputCP(65001);   /* 让中文在 Windows 控制台正确显示 */
#endif
}

'''

#: 完整 C 运行时 prelude = 头段 + 容器段 + 尾段。
#: 三段拆开只为了让容器段能用 `$中文$` 占位符（见 `_C_RUNTIME_CONTAINERS`
#: 上方说明）；真正的拼装在文件末尾 `_c_escape` 定义之后完成 —— 拼装要用它。
#: 对外仍然只有 `_C_RUNTIME` 一个名字，`generate()` 只认这个。
_C_RUNTIME: str = ""     # 在文件末尾赋真值（见「C 运行时拼装」一节）



# ---------------------------------------------------------------------------
# 生成器
# ---------------------------------------------------------------------------

class _FuncInfo:
    """一个顶层用户函数的编译信息（T2a）。

    字段
        name        极快函数名（可含中文）
        c_name      映射后的 C 函数名（jk_fnN）
        params      极快形参名列表
        c_params    形参对应的 C 标识符列表（jk_paN），与 params 同序
        scope       函数作用域：极快名 → C 标识符（形参 + 函数局部变量）
        locals      [(C 标识符, 极快名)]，供在函数体开头统一声明
        body        函数体语句列表
        node        原 FuncDef 节点（报错定位用）
    """

    def __init__(self, name: str, c_name: str, params: List[str],
                 body: List[Node], node: Node) -> None:
        self.name = name
        self.c_name = c_name
        self.params = list(params)
        self.c_params: List[str] = []
        self.scope: Dict[str, str] = {}
        self.locals: List[tuple] = []
        self.body = body
        self.node = node

    def signature(self) -> str:
        """C 声明头。零参函数写 `(void)`，避免旧式「未指定参数」声明。"""
        if not self.c_params:
            return "static JKValue {}(void)".format(self.c_name)
        return "static JKValue {}({})".format(
            self.c_name, ", ".join("JKValue {}".format(p) for p in self.c_params)
        )


class CCodegen:
    """把受支持子集的 AST 翻译为 C 源码。

    变量模型
    --------
    极快的**顶层**变量编译为 C 的**文件作用域** `static JKValue`：先扫全部
    顶层语句（含嵌套块）收集每个被 `定义`/赋值 的名字，在 prelude 之后统一
    声明，再按语句序逐条赋值。

    T2a 之前它们是 `main()` 的局部变量；有了用户函数就必须提到文件作用域
    —— 函数体要能读写全局（见下面「函数与全局」）。静态存储期变量零初始化，
    而 `JK_NIL` 的 tag 恰好是 0、`v.i` 也是 0，所以零初始化**等价**
    `jk_nil()`，不需要额外的初始化代码。

    这样做有四个好处：
      1. 重复 `定义` 同名变量不会撞 C 的重复声明；
      2. 循环体里赋的值在循环外仍可见 —— 与解释器的作用域语义一致
         （极快的 `如果`/`当`/`重复` 块**不**引入新作用域）；
      3. 每个槽位都预初始化为 nil，读到「还没走到那条赋值」的变量时
         行为是确定的（nil），不会读未初始化内存；
      4. 顶层函数可以直接按名字读写它们。

    函数与全局（T2a）
    ----------------
    顶层 `函数 名 接收 形参：...` 编译为 `static JKValue jk_fnN(JKValue ...)`。
    所有函数**先前向声明再发射函数体**，因此互递归（甲 调 乙、乙 调 甲）可用。

    函数体内一个名字的解析顺序（与解释器 `Environment` 的查找链一致）：

      1. 形参 → C 形参；
      2. 该函数内被 `定义`/赋值 且**不是**全局的名字 → C 函数局部变量；
      3. 全局名 → 文件作用域 static 变量。

    第 3 条同时决定了**写**语义：解释器的 `定义`/`赋值` 都先走
    `Environment.update`（沿作用域链向上找），找到全局就**改全局**，只有
    整条链都没有才在本层新建。AOT 照抄这个语义 —— 函数里 `定义 全局名 = X`
    改的是全局，不是新建局部。

    不支持闭包：嵌套 `FuncDef` 与 `Lambda` 由 subset_gate 拦在门外
    （JK-E7001）；codegen 侧也留了兜底 CodegenError。

    定值分析（M9-3 放宽）
    --------------------
    加入控制流后，「某变量是否已赋值」不再能靠直线扫描判死：
    `如果 ... 那么：定义 赵甲 = 1。。` 之后读 `赵甲` 在静态上既可能
    已赋值也可能没有。因此把检查从「**必然**已赋值」放宽为
    「**全程序某处**被赋值」——真正的拼写错误（名字压根没出现在任何
    赋值左侧）仍会被抓住，而合法的条件赋值不再误报。
    """

    def __init__(self) -> None:
        self._globals: Dict[str, str] = {}    # 顶层变量名 → C 标识符
        self._funcs: Dict[str, _FuncInfo] = {}   # 函数名 → 编译信息
        self._func_order: List[_FuncInfo] = []   # 保持源码书写顺序
        self._main_body: List[Node] = []     # 顶层非函数定义语句
        self._scope = None                   # 当前函数作用域；None = main 体内
        self._loop_vars: Dict[str, str] = {}  # T2b：遍历循环变量名 → C 标识符
        self._lines: List[str] = []
        self._indent = 1                     # 当前缩进层级（1 = 函数体内）
        self._loop_depth = 0                 # 循环嵌套深度（校验 跳出/跳过）
        self._tmp_seq = 0                    # 临时变量序号

    # ---- 入口 ----

    def generate(self, program: Program) -> str:
        self._globals = {}
        self._funcs = {}
        self._func_order = []
        self._main_body = []
        self._scope = None
        self._loop_vars = {}
        self._lines = []
        self._indent = 1
        self._loop_depth = 0
        self._tmp_seq = 0

        self._collect_program(program)

        parts = [_C_RUNTIME]

        if self._globals:
            parts.append(
                "/* ---------- 顶层变量 ----------\n"
                " * 文件作用域 static：零初始化即 tag=JK_NIL、v.i=0，等价 jk_nil()。\n"
                " * 提到文件作用域是为了让顶层函数能直接读写（AOT 无闭包）。\n"
                " */\n"
            )
            for name, slot in self._globals.items():
                parts.append("static JKValue {};   /* {} */\n".format(slot, name))
            parts.append("\n")

        if self._func_order:
            parts.append(
                "/* ---------- 用户函数前向声明 ----------\n"
                " * 先声明再定义，互递归与「先调用后定义」都能过编译。\n"
                " */\n"
            )
            for info in self._func_order:
                parts.append("{};   /* {} */\n".format(info.signature(), info.name))
            parts.append("\n")
            for info in self._func_order:
                parts.append(self._emit_function(info))

        self._lines = []
        self._indent = 1
        self._loop_depth = 0
        self._scope = None
        self._emit_body(self._main_body)

        parts.append("int main(void)\n{\n    jk_init_console();\n")
        parts.append("\n".join(self._lines))
        parts.append("\n    return 0;\n}\n")
        return "".join(parts)

    # ---- 预扫：顶层函数、全局槽位、函数作用域 ----

    def _collect_program(self, program: Program) -> None:
        """把顶层语句分成「函数定义」与「main 体」，再分配各级槽位。

        顺序不可调换：**先**收全局，**后**分配函数局部 —— 函数里给全局名
        赋值改的是全局，只有非全局名才需要新建局部（见类文档「函数与全局」）。
        """
        for stmt in program.body:
            if isinstance(stmt, FuncDef):
                self._register_func(stmt)
            else:
                self._main_body.append(stmt)

        self._collect_slots(self._main_body)

        # 函数名与顶层变量名撞车：静态绑定说不清「这个名字现在是函数还是变量」
        clash = sorted(set(self._funcs) & set(self._globals))
        if clash:
            raise CodegenError(
                "名字 {} 既是顶层函数名又是顶层变量名，AOT 无法静态绑定"
                .format("、".join(clash))
            )

        for info in self._func_order:
            self._collect_func_scope(info)

    def _register_func(self, node: FuncDef) -> None:
        if node.name in self._funcs:
            raise CodegenError(
                "重复定义的函数：{}（解释器是后定义覆盖前者，AOT 静态绑定无法表达，"
                "请改名）".format(node.name)
            )
        info = _FuncInfo(
            name=node.name,
            c_name="jk_fn{}".format(len(self._func_order) + 1),
            params=node.params,
            body=node.body,
            node=node,
        )
        self._funcs[node.name] = info
        self._func_order.append(info)

    def _collect_func_scope(self, info: _FuncInfo) -> None:
        """给一个函数的形参与局部变量分配 C 标识符。

        形参优先（解释器的 call_env 里就有它们，`update` 先命中本层）；
        其余被赋值的名字若是全局就复用全局槽位（不进 scope，由 `_slot`
        兜到 `_globals`），否则新建函数局部。
        """
        for index, param in enumerate(info.params):
            c_name = "jk_pa{}_{}".format(info.c_name[5:], index + 1)
            info.c_params.append(c_name)
            # 同名形参（`接收 甲 甲`）：后者覆盖前者，与解释器 set 的行为一致
            info.scope[param] = c_name

        assigned: List[str] = []
        _scan_assigned_names(info.body, assigned)
        for name in assigned:
            if name in info.scope or name in self._globals:
                continue
            c_name = "jk_lv{}_{}".format(info.c_name[5:], len(info.locals) + 1)
            info.scope[name] = c_name
            info.locals.append((c_name, name))

    # ---- 变量槽位 ----

    def _collect_slots(self, body: List[Node]) -> None:
        """递归预扫顶层语句列表，给每个被定义/赋值的名字分配一个 C 标识符。

        极快标识符可以是中文，不能直接当 C 标识符，因此统一映射为 jk_varN，
        并在声明处用注释保留原名，方便读生成的 C。

        必须**递归进嵌套块**：`当 ...：定义 赵甲 = 1。。` 里的 `赵甲`
        也要拿到槽位，否则 codegen 到那一行时会报「未分配槽位」。
        """
        names: List[str] = []
        _scan_assigned_names(body, names)
        for name in names:
            if name not in self._globals:
                self._globals[name] = "jk_var{}".format(len(self._globals) + 1)

    # ---- 函数体 ----

    def _emit_function(self, info: _FuncInfo) -> str:
        """发射一个顶层函数的完整定义（签名 + 花括号 + 体）。"""
        self._lines = []
        self._indent = 1
        self._loop_depth = 0
        self._scope = info.scope

        for c_name, jk_name in info.locals:
            self._line("JKValue {} = jk_nil();   /* {} */".format(c_name, jk_name))
        if info.locals:
            self._lines.append("")

        self._emit_body(info.body)
        # 兜底 return：函数体走完没碰到 `返回` 时给 空，与解释器
        # `_call_function` 末尾 `return None` 一致。同时保证 C 的所有
        # 控制流路径都有返回值。
        self._line("return jk_nil();   /* 隐式返回 空 */")

        body = "\n".join(self._lines)
        self._lines = []
        self._scope = None
        return "{}   /* {} */\n{{\n{}\n}}\n\n".format(
            info.signature(), info.name, body)

    # ---- 语句 ----

    def _line(self, text: str) -> None:
        """按当前缩进层级追加一行 C 代码。"""
        self._lines.append("    " * self._indent + text)

    def _next_tmp(self, prefix: str) -> str:
        self._tmp_seq += 1
        return "{}{}".format(prefix, self._tmp_seq)

    def _emit_body(self, body: List[Node]) -> None:
        for stmt in body:
            self._emit_stmt(stmt)

    def _emit_block(self, body: List[Node]) -> None:
        """在花括号里发射一个语句块（缩进 +1）。空体补 `/* 空 */` 保持合法 C。"""
        self._indent += 1
        if body:
            self._emit_body(body)
        else:
            self._line("/* 空块 */")
        self._indent -= 1

    def _emit_stmt(self, node: Node) -> None:
        if isinstance(node, Define):
            expr = self._expr(node.value)
            self._line("{} = {};".format(self._slot(node.name), expr))
            return

        if isinstance(node, Assign):
            target = node.target
            if isinstance(target, Index):
                # 下标写顺延（ADR-37 §2.3）。门禁的「赋值目标 索引访问」规则
                # 应该已经拦住了；这里兜底，且把 ADR 出处写进消息，避免用户
                # 以为是 codegen 的 bug。
                raise CodegenError(
                    "AOT 第一切片不支持下标写入（`列表[i] = 值`）：顺延项，"
                    "见 ADR-37 §2.3；下标读取（`列表[i]` 取值）是支持的"
                )
            if not isinstance(target, Ident):
                raise CodegenError(
                    "赋值目标必须是变量名，收到 {}".format(type(target).__name__)
                )
            expr = self._expr(node.value)
            self._line("{} = {};".format(self._slot(target.name), expr))
            return


        if isinstance(node, If):
            self._emit_if(node)
            return

        if isinstance(node, While):
            self._emit_while(node)
            return

        if isinstance(node, For):
            self._emit_for(node)
            return

        if isinstance(node, Repeat):
            self._emit_repeat(node)
            return

        if isinstance(node, Break):
            if self._loop_depth == 0:
                raise CodegenError("「跳出」只能出现在循环体内")
            self._line("break;")
            return

        if isinstance(node, Continue):
            if self._loop_depth == 0:
                raise CodegenError("「跳过」只能出现在循环体内")
            self._line("continue;")
            return

        if isinstance(node, Return):
            self._emit_return(node)
            return

        if isinstance(node, FuncDef):
            # 顶层的 FuncDef 已在 _collect_program 中提取；如果走到这里
            # 说明它出现在函数体/块体里（嵌套），subset_gate 应该已经拦住了，
            # 但 codegen 也留兜底。
            raise CodegenError(
                "AOT 不支持嵌套函数定义：{}（请把它移到顶层）".format(node.name)
            )

        if isinstance(node, FuncCall):
            # 顶层裸函数调用当语句（丢弃返回值）
            self._line("(void)({});".format(self._expr(node)))
            return

        if isinstance(node, Call) and node.verb == "打印":
            self._emit_print(node)
            return

        if isinstance(node, Call):
            # 顶层裸表达式：求值后丢弃（保留可能的副作用，如除零停机）
            self._line("(void)({});".format(self._expr(node)))
            return

        if isinstance(node, (ListLit, DictLit, Index)):
            # 单独一行的容器字面量 / 下标取值：求值后丢弃，与解释器一样保留
            # 副作用（下标越界照样停机），不能因为「结果没人要」就跳过。
            self._line("(void)({});".format(self._expr(node)))
            return


        raise CodegenError("AOT 不支持的语句：{}".format(type(node).__name__))

    def _emit_return(self, node: Return) -> None:
        """发射 `返回` 语句。与解释器一致：无值时返回 空（nil）。"""
        if self._scope is None:
            raise CodegenError("「返回」只能出现在函数体内")
        if node.value is not None:
            self._line("return {};".format(self._expr(node.value)))
        else:
            self._line("return jk_nil();")


    def _emit_if(self, node: If) -> None:
        """`如果 / 否则如果 / 否则` → C 的 if / else if / else 链。

        条件统一过 `jk_truthy()`，与解释器的 Python 真值语义对齐
        （空 / 假 / 0 / 0.0 / "" 为假）。
        """
        self._line("if (jk_truthy({})) {{".format(self._expr(node.cond)))
        self._emit_block(node.then_branch)

        for cond, body in (node.elif_branches or []):
            self._line("}} else if (jk_truthy({})) {{".format(self._expr(cond)))
            self._emit_block(body)

        if node.else_branch is not None:
            self._line("} else {")
            self._emit_block(node.else_branch)

        self._line("}")

    def _emit_while(self, node: While) -> None:
        """`当 条件：...` → C 的 while。条件每轮重新求值。"""
        self._line("while (jk_truthy({})) {{".format(self._expr(node.cond)))
        self._loop_depth += 1
        self._emit_block(node.body)
        self._loop_depth -= 1
        self._line("}")

    def _emit_repeat(self, node: Repeat) -> None:
        """`重复 N 次：...` → 计数 for。

        次数**只在进入前求值一次**（与解释器 `range(n)` 一致），
        因此用一个临时 long long 存住，循环体里改动源表达式里的变量
        不会影响剩余轮数。
        """
        count_var = self._next_tmp("jk_cnt")
        idx_var = self._next_tmp("jk_i")
        self._line("{{ long long {} = jk_as_int({});".format(
            count_var, self._expr(node.count)))
        self._indent += 1
        self._line("for (long long {i} = 0; {i} < {n}; {i}++) {{".format(
            i=idx_var, n=count_var))
        self._loop_depth += 1
        self._emit_block(node.body)
        self._loop_depth -= 1
        self._line("}")
        self._indent -= 1
        self._line("}")

    def _emit_for(self, node: For) -> None:
        """T2b：`遍历 变量 于 范围(...)` / `遍历 变量 于 【字面量列表】` → C 循环。

        子集门禁（`subset_gate._collect` 里的 For 分支）保证 `node.iterable` 只可能
        是 `Call(verb="范围", args=[...])` 或 `ListLit(items=[...])`；其它形态在
        gate 阶段已被 JK-E7001 挡下。这里直接按两种形态分发，遇到意外形态则兜底
        抛 CodegenError（不静默产出错语义的代码）。

        循环变量的作用域
        ----------------
        解释器每一轮都 `loop_env = Environment(env); loop_env.set(node.var, item)`，
        循环变量**只在体内可见**，且与外层同名变量互不影响（写只落在子环境）。
        AOT 侧用 `self._loop_vars` 覆盖表模拟「最内层优先」的名字解析：进入循环前
        把 `变量名 → C 局部` 记进去（并保存旧值以支持同名嵌套），退出时恢复。
        C 里对应地把循环变量声明在 for 块内，天然离开作用域。

        范围（Range）
        ------------
        起 / 止 / 步 **在进入循环前只求值一次**（复刻 Python `range` 的语义）：
        循环体里改动源表达式里的变量不会影响剩余轮数。步为 0 是运行期错误
        （解释器里也是 `ValueError: range() arg 3 must not be zero`），
        因此发射一条 `jk_fatal` 兜底；步为正用 `ix < end`，为负用 `ix > end`，
        用一个三元表达式统一表达，避免展开成两份重复代码。

        字面量列表（ListLit）
        --------------------
        列表元素在栈上组成 `JKValue arr[N]`，用下标遍历，**不落堆**。空列表零轮 —
        C 不允许零长度数组初始化，故直接短路成一段注释。列表元素在进入循环前
        求值一次并存进数组，与解释器同构。
        """
        loop_var_name = node.var
        iterable = node.iterable

        if isinstance(iterable, Call) and getattr(iterable, "verb", "") == RANGE_VERB:
            args = list(iterable.args)
            if len(args) not in RANGE_ARITY:
                # 门禁应已拦下；这里兜底防止 AST 构造器绕过 gate。
                raise CodegenError(
                    "范围(...) 参数个数不合法（收到 {} 个，AOT 支持 1~3 个）"
                    .format(len(args))
                )
            if len(args) == 1:
                start_expr = "jk_int(0LL)"
                end_expr = self._expr(args[0])
                step_expr = "jk_int(1LL)"
            elif len(args) == 2:
                start_expr = self._expr(args[0])
                end_expr = self._expr(args[1])
                step_expr = "jk_int(1LL)"
            else:  # 3
                start_expr = self._expr(args[0])
                end_expr = self._expr(args[1])
                step_expr = self._expr(args[2])

            start_tmp = self._next_tmp("jk_rs")
            end_tmp = self._next_tmp("jk_re")
            step_tmp = self._next_tmp("jk_rp")
            idx_tmp = self._next_tmp("jk_ri")
            loop_c = self._next_tmp("jk_lv")

            self._line("{{ long long {} = jk_as_int({});".format(start_tmp, start_expr))
            self._line("  long long {} = jk_as_int({});".format(end_tmp, end_expr))
            self._line("  long long {} = jk_as_int({});".format(step_tmp, step_expr))
            self._line('  if ({} == 0) jk_fatal("{}");'.format(
                step_tmp, _c_escape("错误：范围的步长不能为零")))
            self._indent += 1
            self._line(
                "for (long long {i} = {s}; "
                "({p} > 0) ? ({i} < {e}) : ({i} > {e}); "
                "{i} += {p}) {{".format(
                    i=idx_tmp, s=start_tmp, e=end_tmp, p=step_tmp,
                )
            )
            self._indent += 1
            self._line("JKValue {} = jk_int({});   /* {} */".format(
                loop_c, idx_tmp, loop_var_name))
            self._indent -= 1
            prev = self._loop_vars.pop(loop_var_name, None)
            self._loop_vars[loop_var_name] = loop_c
            self._loop_depth += 1
            self._emit_block(node.body)
            self._loop_depth -= 1
            if prev is None:
                self._loop_vars.pop(loop_var_name, None)
            else:
                self._loop_vars[loop_var_name] = prev
            self._line("}")
            self._indent -= 1
            self._line("}")
            return

        if isinstance(iterable, ListLit):
            items = list(iterable.items)
            if not items:
                self._line("/* 空列表遍历：零轮，无需生成循环 */")
                return
            arr_tmp = self._next_tmp("jk_farr")
            idx_tmp = self._next_tmp("jk_fi")
            loop_c = self._next_tmp("jk_lv")
            args_c = ", ".join(self._expr(item) for item in items)
            self._line("{{ JKValue {}[] = {{ {} }};".format(arr_tmp, args_c))
            self._indent += 1
            self._line(
                "for (long long {i} = 0; {i} < {n}; {i}++) {{".format(
                    i=idx_tmp, n=len(items),
                )
            )
            self._indent += 1
            self._line("JKValue {} = {}[{}];   /* {} */".format(
                loop_c, arr_tmp, idx_tmp, loop_var_name))
            self._indent -= 1
            prev = self._loop_vars.pop(loop_var_name, None)
            self._loop_vars[loop_var_name] = loop_c
            self._loop_depth += 1
            self._emit_block(node.body)
            self._loop_depth -= 1
            if prev is None:
                self._loop_vars.pop(loop_var_name, None)
            else:
                self._loop_vars[loop_var_name] = prev
            self._line("}")
            self._indent -= 1
            self._line("}")
            return

        raise CodegenError(
            "AOT 只支持 `遍历 变量 于 范围(...)` 或 `遍历 变量 于 【字面量列表】`；"
            "收到 iterable={}".format(type(iterable).__name__)
        )

    def _emit_print(self, node: Call) -> None:
        """打印是变参：多参数用空格分隔，末尾换行（与解释器 print(*args) 一致）。"""
        if not node.args:
            self._line("jk_print(0, NULL);")
            return
        args = [self._expr(a) for a in node.args]
        tmp = self._next_tmp("jk_args")
        self._line(
            "{{ JKValue {}[] = {{ {} }}; jk_print({}, {}); }}".format(
                tmp, ", ".join(args), len(args), tmp
            )
        )


    # ---- 表达式 ----

    def _expr(self, node: Node) -> str:
        if isinstance(node, NumberLit):
            value = node.value
            if isinstance(value, bool):
                return "jk_bool({})".format(1 if value else 0)
            if isinstance(value, int):
                return "jk_int({}LL)".format(value)
            return "jk_float({})".format(_c_double(float(value)))

        if isinstance(node, MoneyLit):
            return "jk_rmb({}LL)".format(_to_fen(node.value))

        if isinstance(node, StringLit):
            return 'jk_str("{}")'.format(_c_escape(node.value))

        if isinstance(node, BoolLit):
            return "jk_bool({})".format(1 if node.value else 0)

        if isinstance(node, NilLit):
            return "jk_nil()"

        if isinstance(node, Ident):
            # 名字解析：函数作用域（形参 + 局部）优先，其次全局槽位。
            # 拼错的名字（既不在作用域也从未出现在任何赋值左侧）会被抓住。
            # 槽位都预初始化为 jk_nil()，所以「条件分支里才赋值」的变量
            # 提前读到的是 nil，行为确定，不会读未初始化内存。
            return self._read_name(node.name)

        if isinstance(node, ListLit):
            return self._list_lit(node)

        if isinstance(node, DictLit):
            return self._dict_lit(node)

        if isinstance(node, Index):
            # 下标**读**（ADR-37 §2.3）。写在 `Assign` 里被门禁拦下，
            # codegen 的 `_emit_stmt` 也有兜底，所以这里只会是读。
            return "jk_index({}, {})".format(
                self._expr(node.obj), self._expr(node.index))

        if isinstance(node, FuncCall):
            return self._func_call(node)

        if isinstance(node, Call):
            return self._call(node)

        raise CodegenError("AOT 不支持的表达式：{}".format(type(node).__name__))

    def _list_lit(self, node: ListLit) -> str:
        """`【a，b，c】` → `jk_list_of(3, a, b, c)`（W104 · ADR-37 §2.4）。

        为什么用可变参数而不是「临时变量 + 逐元素赋值」
        --------------------------------------------
        `_expr` 的返回值会被塞进 `while (jk_truthy(...))` / `if (...)` /
        `for (...;...;...)` 的**头部** —— 那些位置插不进语句。而且循环条件每轮
        都要重新求值，若先落成语句再引用临时变量，语义就从「每轮重建」变成
        「只建一次」，直接错。所以列表/字典字面量必须编译成**纯表达式**；
        `jk_list_of` / `jk_dict_of` 的 varargs 形态正好满足，还顺手解决了
        「C 不允许零长度数组初始化」（空列表 → `jk_list_of(0)`）这个坑
        —— `_emit_for` 当年为此不得不短路掉整个循环。

        varargs 传结构体是标准 C：JKValue 不受默认实参提升影响，gcc/clang/MSVC
        行为一致；也避开了复合字面量 `(JKValue[]){...}` 在 MSVC C 模式下的
        可移植性问号。
        """
        items = [self._expr(item) for item in node.items]
        if not items:
            return "jk_list_of(0)"
        return "jk_list_of({}, {})".format(len(items), ", ".join(items))

    def _dict_lit(self, node: DictLit) -> str:
        """`{k：v，...}` → `jk_dict_of(2, k1, v1, k2, v2)`（键值交替传入）。

        键值**按源码顺序**交替传参，`jk_dict_set` 逐对写入 —— 这样重复键的
        「覆盖值、保留首次插入位置」与打印时的插入序都和 Python dict 一致。
        键限标量（ADR-37 §2.4）：字面量形态的容器键由门禁拦，变量形态由
        `jk_dict_set` 在运行期拦。
        """
        flat: List[str] = []
        for pair in node.items:
            key_node, value_node = pair[0], pair[1]
            flat.append(self._expr(key_node))
            flat.append(self._expr(value_node))
        if not flat:
            return "jk_dict_of(0)"
        return "jk_dict_of({}, {})".format(len(node.items), ", ".join(flat))


    def _func_call(self, node: FuncCall) -> str:
        """用户函数调用：`名字(实参...)` → `jk_fnN(实参...)`。

        只支持按名直接调用顶层函数（`node.func` 必须是 `Ident`），与
        subset_gate「间接函数调用」拒绝规则一致。实参数量按解释器语义处理：
        少给的形参在解释器里是 `None`（→ 这里补 `jk_nil()`），多给的丢弃。
        """
        callee = node.func
        if not isinstance(callee, Ident):
            raise CodegenError(
                "AOT 只支持按名直接调用顶层函数，收到 {}"
                .format(type(callee).__name__)
            )
        info = self._funcs.get(callee.name)
        if info is None:
            raise CodegenError(
                "调用了未定义的函数：{}（AOT 只识别顶层 `函数` 定义）"
                .format(callee.name)
            )
        args = [self._expr(a) for a in node.args]
        # 形参多于实参：补 nil，对齐解释器 `args[i] if i < len(args) else None`
        while len(args) < len(info.c_params):
            args.append("jk_nil()")
        # 实参多于形参：截断丢弃多余的
        args = args[:len(info.c_params)]
        return "{}({})".format(info.c_name, ", ".join(args))

    def _read_name(self, name: str) -> str:
        """读取一个名字对应的 C 表达式（右值）。"""
        # T2b：遍历循环变量最内层优先 —— 与解释器 `loop_env = Environment(env);
        # loop_env.set(node.var, item)` 的「子作用域先命中」语义一致。
        if name in self._loop_vars:
            return self._loop_vars[name]
        if self._scope is not None and name in self._scope:
            return self._scope[name]
        if name in self._globals:
            return self._globals[name]
        if name in self._funcs:
            raise CodegenError(
                "函数 {0} 不能当作值使用：AOT 没有函数值与闭包，只支持 "
                "`{0}(实参...)` 这种直接调用".format(name)
            )
        raise CodegenError(
            "未定义的名称：{}（该名字在当前作用域与全局里都未被「定义」或赋值）"
            .format(name)
        )


    def _call(self, node: Call) -> str:
        verb = node.verb

        if verb == "打印":
            raise CodegenError("「打印」只能作为语句使用，不能当表达式取值")

        if verb in _UNARY_OPS:
            if len(node.args) != 1:
                raise CodegenError(
                    "动词 {} 需要 1 个参数，收到 {}".format(verb, len(node.args))
                )
            return "{}({})".format(_UNARY_OPS[verb], self._expr(node.args[0]))

        if verb in _BINARY_OPS:
            if len(node.args) != 2:
                raise CodegenError(
                    "动词 {} 需要 2 个参数，收到 {}".format(verb, len(node.args))
                )
            return "{}({}, {})".format(
                _BINARY_OPS[verb],
                self._expr(node.args[0]),
                self._expr(node.args[1]),
            )

        raise CodegenError("AOT 不支持的内建动词：{}".format(verb))

    # ---- 工具 ----

    def _slot(self, name: str) -> str:
        """写入槽位：按函数作用域 → 全局的优先级找到对应的 C 标识符。"""
        if self._scope is not None and name in self._scope:
            return self._scope[name]
        slot = self._globals.get(name)
        if slot is None:
            raise CodegenError("内部错误：变量 {} 未分配槽位".format(name))
        return slot


# ---------------------------------------------------------------------------
# 字面量转换
# ---------------------------------------------------------------------------

_CENT = Decimal("0.01")


def _to_fen(value) -> int:
    """元 → 分。在 Python 侧用 Decimal 精确换算，保证字面量零误差。

    与 evaluator.RMB._quantize 同口径：先经 str 进 Decimal（避开 float 的
    二进制表示误差），再 ROUND_HALF_UP 量化到分。
    """
    dec = value if isinstance(value, Decimal) else Decimal(str(value))
    return int(dec.quantize(_CENT, rounding=ROUND_HALF_UP) * 100)


def _c_double(value: float) -> str:
    """输出 C 能精确还原的 double 字面量（repr 给最短往返表示）。"""
    if value != value:
        return "(0.0/0.0)"
    if value == float("inf"):
        return "(1.0/0.0)"
    if value == float("-inf"):
        return "(-1.0/0.0)"
    text = repr(value)
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text


def _c_escape(text: str) -> str:
    """把 Python str 转成 C 字符串字面量内容。

    非 ASCII 一律按 UTF-8 编码后逐字节转成八位十六进制转义（前导反斜杠 x），
    这样生成的 C 不依赖编译器的源字符集设置，gcc -std=c11 与 MSVC 行为一致。
    转义序列后紧跟十六进制字符会被 C 贪婪吞掉，所以每个字节转义后主动断开
    字符串，交由 C 的相邻字面量拼接规则合并。
    """
    out: List[str] = []
    simple = {
        "\\": "\\\\",
        '"': '\\"',
        "\n": "\\n",
        "\r": "\\r",
        "\t": "\\t",
        "\a": "\\a",
        "\b": "\\b",
        "\f": "\\f",
        "\v": "\\v",
        "\0": "\\0",
    }
    for ch in text:
        if ch in simple:
            out.append(simple[ch])
        elif " " <= ch <= "~":
            out.append(ch)
        else:
            for byte in ch.encode("utf-8"):
                out.append('\\x{:02x}" "'.format(byte))
    return "".join(out)


# ---------------------------------------------------------------------------
# C 运行时拼装
# ---------------------------------------------------------------------------

#: 匹配运行时模板里的 `$中文$` 占位符。C 源码本身不含 `$`，所以这个定界符
#: 不会与代码撞车；`[^$]*` 而非 `.*?` 是为了让「少写一个 `$`」立刻表现为
#: 匹配失败（占位符原样留在输出里，编译期就炸），而不是悄悄吞掉一大段代码。
_C_PLACEHOLDER = re.compile(r"\$([^$]*)\$")


def _c_expand(template: str) -> str:
    """把 C 模板里的 `$中文$` 占位符替换成 UTF-8 十六进制转义。

    为什么要这一层：运行时里的中文文案必须逐字对齐解释器（ADR-37 §2.5），
    但写进 C 又必须转义（不依赖编译器源字符集）。手抄一串 `\\xNN` 既读不出
    是什么字、又极易抄错一个字节。于是模板里写人话，转义交给 `_c_escape`
    —— 与字符串字面量走的是**同一个**转义函数，两处永远不会漂移。
    """
    return _C_PLACEHOLDER.sub(lambda m: _c_escape(m.group(1)), template)


# 三段拼成完整 prelude。容器段要用 `_c_escape`，所以拼装必须在它定义之后。
_C_RUNTIME = (
    _C_RUNTIME_HEAD
    + _c_expand(_C_RUNTIME_CONTAINERS)
    + _c_expand(_C_RUNTIME_TAIL)
)

# 自检：占位符必须全部展开干净。漏一个就意味着生成的 C 里带着裸 `$`，
# 那会在用户机器上编译失败——宁可在 import 期就炸。
assert "$" not in _C_RUNTIME, "C 运行时里残留未展开的 $占位符$"



# ---------------------------------------------------------------------------
# 对外接口
# ---------------------------------------------------------------------------

def generate_c(program: Program) -> str:
    """AST → 完整 C 源码字符串。

    调用方**必须**先跑 subset_gate.check 并确认返回 True。
    """
    return CCodegen().generate(program)


# ---------------------------------------------------------------------------
# 静态扫描：抽出「被赋值」的名字（Define / Assign 目标）
# ---------------------------------------------------------------------------

def _scan_assigned_names(body: List[Node], out: List[str]) -> None:
    """把 body 及其嵌套块里所有出现在赋值左侧的名字**按首次出现顺序**追加到 out。

    与主包 `evaluator.Environment.update` 的作用域链语义配合：AOT 侧只需要
    知道「这个名字曾经在这里被写过」就足够；具体它写的是全局还是新建局部，
    由调用方（`_collect_slots` / `_collect_func_scope`）根据上下文决定。

    覆盖：Define / Assign（Ident 目标）以及 If / While / Repeat 的嵌套体。
    有意**不**跨 FuncDef 边界：AOT 无闭包，函数体里赋的名字不外泄。
    """
    seen = set(out)
    def _add(name: str) -> None:
        if name not in seen:
            seen.add(name)
            out.append(name)

    def _walk(nodes: List[Node]) -> None:
        for stmt in nodes:
            if isinstance(stmt, Define):
                _add(stmt.name)
            elif isinstance(stmt, Assign) and isinstance(stmt.target, Ident):
                _add(stmt.target.name)

            if isinstance(stmt, If):
                _walk(stmt.then_branch)
                for _cond, sub_body in (stmt.elif_branches or []):
                    _walk(sub_body)
                if stmt.else_branch:
                    _walk(stmt.else_branch)
            elif isinstance(stmt, (While, Repeat)):
                _walk(stmt.body)
            # FuncDef 边界故意不下钻：其内部赋值只影响函数自身作用域。

    _walk(body)
